namespace Acessos.Usuarios
{
    partial class Usuariosfrm
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle1 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle2 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle3 = new System.Windows.Forms.DataGridViewCellStyle();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Usuariosfrm));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.GridUsuarios = new Bunifu.UI.WinForms.BunifuDataGridView();
            this.radGroupBox1 = new Telerik.WinControls.UI.RadGroupBox();
            this.bunifuLabel7 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel6 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel5 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel4 = new Bunifu.UI.WinForms.BunifuLabel();
            this.txtData = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel3 = new Bunifu.UI.WinForms.BunifuLabel();
            this.cbNivel = new System.Windows.Forms.ComboBox();
            this.bunifuLabel2 = new Bunifu.UI.WinForms.BunifuLabel();
            this.cbCargo = new System.Windows.Forms.ComboBox();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.chkAtivo = new Bunifu.UI.WinForms.BunifuCheckBox();
            this.txtSenha = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtEmail = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtNome = new Bunifu.UI.WinForms.BunifuTextBox();
            this.aquaTheme1 = new Telerik.WinControls.Themes.AquaTheme();
            this.btSalvar = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btAtualizar = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btExcluir = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btNovo = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btDesbloquear = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            ((System.ComponentModel.ISupportInitialize)(this.GridUsuarios)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.radGroupBox1)).BeginInit();
            this.radGroupBox1.SuspendLayout();
            this.SuspendLayout();
            // 
            // GridUsuarios
            // 
            this.GridUsuarios.AllowCustomTheming = false;
            this.GridUsuarios.AllowUserToAddRows = false;
            this.GridUsuarios.AllowUserToDeleteRows = false;
            this.GridUsuarios.AllowUserToResizeColumns = false;
            this.GridUsuarios.AllowUserToResizeRows = false;
            dataGridViewCellStyle1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle1.ForeColor = System.Drawing.Color.Black;
            this.GridUsuarios.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle1;
            this.GridUsuarios.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.GridUsuarios.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.GridUsuarios.BackgroundColor = System.Drawing.Color.LightGray;
            this.GridUsuarios.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.GridUsuarios.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleHorizontal;
            this.GridUsuarios.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle2.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle2.BackColor = System.Drawing.Color.DodgerBlue;
            dataGridViewCellStyle2.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle2.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            dataGridViewCellStyle2.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.GridUsuarios.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle2;
            this.GridUsuarios.ColumnHeadersHeight = 40;
            this.GridUsuarios.CurrentTheme.AlternatingRowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            this.GridUsuarios.CurrentTheme.AlternatingRowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.GridUsuarios.CurrentTheme.AlternatingRowsStyle.ForeColor = System.Drawing.Color.Black;
            this.GridUsuarios.CurrentTheme.AlternatingRowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.GridUsuarios.CurrentTheme.AlternatingRowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            this.GridUsuarios.CurrentTheme.BackColor = System.Drawing.Color.White;
            this.GridUsuarios.CurrentTheme.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.GridUsuarios.CurrentTheme.HeaderStyle.BackColor = System.Drawing.Color.DodgerBlue;
            this.GridUsuarios.CurrentTheme.HeaderStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            this.GridUsuarios.CurrentTheme.HeaderStyle.ForeColor = System.Drawing.Color.White;
            this.GridUsuarios.CurrentTheme.HeaderStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            this.GridUsuarios.CurrentTheme.HeaderStyle.SelectionForeColor = System.Drawing.Color.White;
            this.GridUsuarios.CurrentTheme.Name = null;
            this.GridUsuarios.CurrentTheme.RowsStyle.BackColor = System.Drawing.Color.White;
            this.GridUsuarios.CurrentTheme.RowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.GridUsuarios.CurrentTheme.RowsStyle.ForeColor = System.Drawing.Color.Black;
            this.GridUsuarios.CurrentTheme.RowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.GridUsuarios.CurrentTheme.RowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle3.BackColor = System.Drawing.Color.White;
            dataGridViewCellStyle3.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle3.ForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle3.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.GridUsuarios.DefaultCellStyle = dataGridViewCellStyle3;
            this.GridUsuarios.EnableHeadersVisualStyles = false;
            this.GridUsuarios.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.GridUsuarios.HeaderBackColor = System.Drawing.Color.DodgerBlue;
            this.GridUsuarios.HeaderBgColor = System.Drawing.Color.Empty;
            this.GridUsuarios.HeaderForeColor = System.Drawing.Color.White;
            this.GridUsuarios.Location = new System.Drawing.Point(12, 12);
            this.GridUsuarios.Name = "GridUsuarios";
            this.GridUsuarios.ReadOnly = true;
            this.GridUsuarios.RowHeadersVisible = false;
            this.GridUsuarios.RowTemplate.Height = 40;
            this.GridUsuarios.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.GridUsuarios.ShowCellErrors = false;
            this.GridUsuarios.ShowCellToolTips = false;
            this.GridUsuarios.ShowEditingIcon = false;
            this.GridUsuarios.ShowRowErrors = false;
            this.GridUsuarios.Size = new System.Drawing.Size(981, 280);
            this.GridUsuarios.TabIndex = 0;
            this.GridUsuarios.Theme = Bunifu.UI.WinForms.BunifuDataGridView.PresetThemes.Light;
            this.GridUsuarios.SelectionChanged += new System.EventHandler(this.GridUsuarios_SelectionChanged);
            // 
            // radGroupBox1
            // 
            this.radGroupBox1.AccessibleRole = System.Windows.Forms.AccessibleRole.Grouping;
            this.radGroupBox1.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.radGroupBox1.BackColor = System.Drawing.Color.WhiteSmoke;
            this.radGroupBox1.Controls.Add(this.bunifuLabel7);
            this.radGroupBox1.Controls.Add(this.bunifuLabel6);
            this.radGroupBox1.Controls.Add(this.bunifuLabel5);
            this.radGroupBox1.Controls.Add(this.bunifuLabel4);
            this.radGroupBox1.Controls.Add(this.txtData);
            this.radGroupBox1.Controls.Add(this.bunifuLabel3);
            this.radGroupBox1.Controls.Add(this.cbNivel);
            this.radGroupBox1.Controls.Add(this.bunifuLabel2);
            this.radGroupBox1.Controls.Add(this.cbCargo);
            this.radGroupBox1.Controls.Add(this.bunifuLabel1);
            this.radGroupBox1.Controls.Add(this.chkAtivo);
            this.radGroupBox1.Controls.Add(this.txtSenha);
            this.radGroupBox1.Controls.Add(this.txtEmail);
            this.radGroupBox1.Controls.Add(this.txtNome);
            this.radGroupBox1.Font = new System.Drawing.Font("Verdana", 8F);
            this.radGroupBox1.HeaderText = "Dados do Usuário";
            this.radGroupBox1.Location = new System.Drawing.Point(12, 298);
            this.radGroupBox1.Name = "radGroupBox1";
            this.radGroupBox1.Size = new System.Drawing.Size(736, 235);
            this.radGroupBox1.TabIndex = 1;
            this.radGroupBox1.Text = "Dados do Usuário";
            this.radGroupBox1.ThemeName = "Aqua";
            // 
            // bunifuLabel7
            // 
            this.bunifuLabel7.AllowParentOverrides = false;
            this.bunifuLabel7.AutoEllipsis = false;
            this.bunifuLabel7.CursorType = null;
            this.bunifuLabel7.Font = new System.Drawing.Font("Segoe UI", 10F);
            this.bunifuLabel7.Location = new System.Drawing.Point(351, 32);
            this.bunifuLabel7.Name = "bunifuLabel7";
            this.bunifuLabel7.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel7.Size = new System.Drawing.Size(35, 17);
            this.bunifuLabel7.TabIndex = 13;
            this.bunifuLabel7.Text = "Senha";
            this.bunifuLabel7.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel7.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel6
            // 
            this.bunifuLabel6.AllowParentOverrides = false;
            this.bunifuLabel6.AutoEllipsis = false;
            this.bunifuLabel6.CursorType = null;
            this.bunifuLabel6.Font = new System.Drawing.Font("Segoe UI", 10F);
            this.bunifuLabel6.Location = new System.Drawing.Point(5, 32);
            this.bunifuLabel6.Name = "bunifuLabel6";
            this.bunifuLabel6.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel6.Size = new System.Drawing.Size(102, 17);
            this.bunifuLabel6.TabIndex = 12;
            this.bunifuLabel6.Text = "Nome de usuário";
            this.bunifuLabel6.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel6.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel5
            // 
            this.bunifuLabel5.AllowParentOverrides = false;
            this.bunifuLabel5.AutoEllipsis = false;
            this.bunifuLabel5.CursorType = null;
            this.bunifuLabel5.Font = new System.Drawing.Font("Segoe UI", 10F);
            this.bunifuLabel5.Location = new System.Drawing.Point(5, 100);
            this.bunifuLabel5.Name = "bunifuLabel5";
            this.bunifuLabel5.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel5.Size = new System.Drawing.Size(36, 17);
            this.bunifuLabel5.TabIndex = 11;
            this.bunifuLabel5.Text = "E-mail";
            this.bunifuLabel5.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel5.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel4
            // 
            this.bunifuLabel4.AllowParentOverrides = false;
            this.bunifuLabel4.AutoEllipsis = false;
            this.bunifuLabel4.CursorType = null;
            this.bunifuLabel4.Font = new System.Drawing.Font("Segoe UI", 10F);
            this.bunifuLabel4.Location = new System.Drawing.Point(5, 162);
            this.bunifuLabel4.Name = "bunifuLabel4";
            this.bunifuLabel4.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel4.Size = new System.Drawing.Size(94, 17);
            this.bunifuLabel4.TabIndex = 10;
            this.bunifuLabel4.Text = "Data de Criação";
            this.bunifuLabel4.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel4.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // txtData
            // 
            this.txtData.AcceptsReturn = false;
            this.txtData.AcceptsTab = false;
            this.txtData.AnimationSpeed = 200;
            this.txtData.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtData.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtData.AutoSizeHeight = true;
            this.txtData.BackColor = System.Drawing.Color.AntiqueWhite;
            this.txtData.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtData.BackgroundImage")));
            this.txtData.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtData.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtData.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtData.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtData.BorderRadius = 1;
            this.txtData.BorderThickness = 1;
            this.txtData.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtData.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtData.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtData.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtData.DefaultText = "";
            this.txtData.FillColor = System.Drawing.Color.AntiqueWhite;
            this.txtData.HideSelection = true;
            this.txtData.IconLeft = null;
            this.txtData.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtData.IconPadding = 10;
            this.txtData.IconRight = null;
            this.txtData.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtData.Lines = new string[0];
            this.txtData.Location = new System.Drawing.Point(5, 189);
            this.txtData.MaxLength = 500;
            this.txtData.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtData.Modified = false;
            this.txtData.Multiline = false;
            this.txtData.Name = "txtData";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtData.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtData.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtData.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.AntiqueWhite;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtData.OnIdleState = stateProperties4;
            this.txtData.Padding = new System.Windows.Forms.Padding(3);
            this.txtData.PasswordChar = '\0';
            this.txtData.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtData.PlaceholderText = "";
            this.txtData.ReadOnly = true;
            this.txtData.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtData.SelectedText = "";
            this.txtData.SelectionLength = 0;
            this.txtData.SelectionStart = 0;
            this.txtData.ShortcutsEnabled = true;
            this.txtData.Size = new System.Drawing.Size(492, 39);
            this.txtData.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.txtData.TabIndex = 9;
            this.txtData.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.txtData.TextMarginBottom = 0;
            this.txtData.TextMarginLeft = 3;
            this.txtData.TextMarginTop = 1;
            this.txtData.TextPlaceholder = "";
            this.txtData.UseSystemPasswordChar = false;
            this.txtData.WordWrap = true;
            // 
            // bunifuLabel3
            // 
            this.bunifuLabel3.AllowParentOverrides = false;
            this.bunifuLabel3.AutoEllipsis = false;
            this.bunifuLabel3.CursorType = null;
            this.bunifuLabel3.Font = new System.Drawing.Font("Segoe UI", 10F);
            this.bunifuLabel3.Location = new System.Drawing.Point(525, 127);
            this.bunifuLabel3.Name = "bunifuLabel3";
            this.bunifuLabel3.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel3.Size = new System.Drawing.Size(29, 17);
            this.bunifuLabel3.TabIndex = 8;
            this.bunifuLabel3.Text = "Nivel";
            this.bunifuLabel3.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel3.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // cbNivel
            // 
            this.cbNivel.Font = new System.Drawing.Font("Verdana", 12F);
            this.cbNivel.FormattingEnabled = true;
            this.cbNivel.Items.AddRange(new object[] {
            "1",
            "2",
            "3",
            "4",
            "5"});
            this.cbNivel.Location = new System.Drawing.Point(567, 123);
            this.cbNivel.Name = "cbNivel";
            this.cbNivel.Size = new System.Drawing.Size(121, 26);
            this.cbNivel.TabIndex = 7;
            // 
            // bunifuLabel2
            // 
            this.bunifuLabel2.AllowParentOverrides = false;
            this.bunifuLabel2.AutoEllipsis = false;
            this.bunifuLabel2.CursorType = null;
            this.bunifuLabel2.Font = new System.Drawing.Font("Segoe UI", 10F);
            this.bunifuLabel2.Location = new System.Drawing.Point(353, 127);
            this.bunifuLabel2.Name = "bunifuLabel2";
            this.bunifuLabel2.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel2.Size = new System.Drawing.Size(39, 17);
            this.bunifuLabel2.TabIndex = 6;
            this.bunifuLabel2.Text = "Cargo:";
            this.bunifuLabel2.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel2.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // cbCargo
            // 
            this.cbCargo.Enabled = false;
            this.cbCargo.Font = new System.Drawing.Font("Verdana", 12F);
            this.cbCargo.FormattingEnabled = true;
            this.cbCargo.Items.AddRange(new object[] {
            "Admin ",
            "Gerente ",
            "Supervisor",
            "Encarregado",
            "Comum"});
            this.cbCargo.Location = new System.Drawing.Point(398, 123);
            this.cbCargo.Name = "cbCargo";
            this.cbCargo.Size = new System.Drawing.Size(121, 26);
            this.cbCargo.TabIndex = 5;
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.Font = new System.Drawing.Font("Segoe UI", 12F);
            this.bunifuLabel1.Location = new System.Drawing.Point(567, 184);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(47, 21);
            this.bunifuLabel1.TabIndex = 4;
            this.bunifuLabel1.Text = "Ativo ?";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // chkAtivo
            // 
            this.chkAtivo.AllowBindingControlAnimation = true;
            this.chkAtivo.AllowBindingControlColorChanges = false;
            this.chkAtivo.AllowBindingControlLocation = true;
            this.chkAtivo.AllowCheckBoxAnimation = true;
            this.chkAtivo.AllowCheckmarkAnimation = true;
            this.chkAtivo.AllowOnHoverStates = true;
            this.chkAtivo.AutoCheck = true;
            this.chkAtivo.BackColor = System.Drawing.Color.Transparent;
            this.chkAtivo.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("chkAtivo.BackgroundImage")));
            this.chkAtivo.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Zoom;
            this.chkAtivo.BindingControlPosition = Bunifu.UI.WinForms.BunifuCheckBox.BindingControlPositions.Right;
            this.chkAtivo.BorderRadius = 12;
            this.chkAtivo.Checked = false;
            this.chkAtivo.CheckState = Bunifu.UI.WinForms.BunifuCheckBox.CheckStates.Indeterminate;
            this.chkAtivo.Cursor = System.Windows.Forms.Cursors.Default;
            this.chkAtivo.CustomCheckmarkImage = null;
            this.chkAtivo.Location = new System.Drawing.Point(635, 184);
            this.chkAtivo.MinimumSize = new System.Drawing.Size(17, 17);
            this.chkAtivo.Name = "chkAtivo";
            this.chkAtivo.OnCheck.BorderColor = System.Drawing.Color.DodgerBlue;
            this.chkAtivo.OnCheck.BorderRadius = 12;
            this.chkAtivo.OnCheck.BorderThickness = 2;
            this.chkAtivo.OnCheck.CheckBoxColor = System.Drawing.Color.DodgerBlue;
            this.chkAtivo.OnCheck.CheckmarkColor = System.Drawing.Color.White;
            this.chkAtivo.OnCheck.CheckmarkThickness = 2;
            this.chkAtivo.OnDisable.BorderColor = System.Drawing.Color.LightGray;
            this.chkAtivo.OnDisable.BorderRadius = 12;
            this.chkAtivo.OnDisable.BorderThickness = 2;
            this.chkAtivo.OnDisable.CheckBoxColor = System.Drawing.Color.Transparent;
            this.chkAtivo.OnDisable.CheckmarkColor = System.Drawing.Color.LightGray;
            this.chkAtivo.OnDisable.CheckmarkThickness = 2;
            this.chkAtivo.OnHoverChecked.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.chkAtivo.OnHoverChecked.BorderRadius = 12;
            this.chkAtivo.OnHoverChecked.BorderThickness = 2;
            this.chkAtivo.OnHoverChecked.CheckBoxColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.chkAtivo.OnHoverChecked.CheckmarkColor = System.Drawing.Color.White;
            this.chkAtivo.OnHoverChecked.CheckmarkThickness = 2;
            this.chkAtivo.OnHoverUnchecked.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.chkAtivo.OnHoverUnchecked.BorderRadius = 12;
            this.chkAtivo.OnHoverUnchecked.BorderThickness = 1;
            this.chkAtivo.OnHoverUnchecked.CheckBoxColor = System.Drawing.Color.Transparent;
            this.chkAtivo.OnUncheck.BorderColor = System.Drawing.Color.DarkGray;
            this.chkAtivo.OnUncheck.BorderRadius = 12;
            this.chkAtivo.OnUncheck.BorderThickness = 1;
            this.chkAtivo.OnUncheck.CheckBoxColor = System.Drawing.Color.Transparent;
            this.chkAtivo.Size = new System.Drawing.Size(23, 23);
            this.chkAtivo.Style = Bunifu.UI.WinForms.BunifuCheckBox.CheckBoxStyles.Bunifu;
            this.chkAtivo.TabIndex = 3;
            this.chkAtivo.ThreeState = false;
            this.chkAtivo.ToolTipText = null;
            // 
            // txtSenha
            // 
            this.txtSenha.AcceptsReturn = false;
            this.txtSenha.AcceptsTab = false;
            this.txtSenha.AnimationSpeed = 200;
            this.txtSenha.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtSenha.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtSenha.AutoSizeHeight = true;
            this.txtSenha.BackColor = System.Drawing.Color.White;
            this.txtSenha.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtSenha.BackgroundImage")));
            this.txtSenha.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtSenha.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtSenha.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtSenha.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtSenha.BorderRadius = 1;
            this.txtSenha.BorderThickness = 1;
            this.txtSenha.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtSenha.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtSenha.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtSenha.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtSenha.DefaultText = "";
            this.txtSenha.FillColor = System.Drawing.Color.White;
            this.txtSenha.HideSelection = true;
            this.txtSenha.IconLeft = null;
            this.txtSenha.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtSenha.IconPadding = 10;
            this.txtSenha.IconRight = null;
            this.txtSenha.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtSenha.Lines = new string[0];
            this.txtSenha.Location = new System.Drawing.Point(349, 55);
            this.txtSenha.MaxLength = 500;
            this.txtSenha.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtSenha.Modified = false;
            this.txtSenha.Multiline = false;
            this.txtSenha.Name = "txtSenha";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtSenha.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtSenha.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtSenha.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtSenha.OnIdleState = stateProperties8;
            this.txtSenha.Padding = new System.Windows.Forms.Padding(3);
            this.txtSenha.PasswordChar = '\0';
            this.txtSenha.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtSenha.PlaceholderText = "";
            this.txtSenha.ReadOnly = false;
            this.txtSenha.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtSenha.SelectedText = "";
            this.txtSenha.SelectionLength = 0;
            this.txtSenha.SelectionStart = 0;
            this.txtSenha.ShortcutsEnabled = true;
            this.txtSenha.Size = new System.Drawing.Size(341, 39);
            this.txtSenha.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtSenha.TabIndex = 2;
            this.txtSenha.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtSenha.TextMarginBottom = 0;
            this.txtSenha.TextMarginLeft = 3;
            this.txtSenha.TextMarginTop = 1;
            this.txtSenha.TextPlaceholder = "";
            this.txtSenha.UseSystemPasswordChar = true;
            this.txtSenha.WordWrap = true;
            // 
            // txtEmail
            // 
            this.txtEmail.AcceptsReturn = false;
            this.txtEmail.AcceptsTab = false;
            this.txtEmail.AnimationSpeed = 200;
            this.txtEmail.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtEmail.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtEmail.AutoSizeHeight = true;
            this.txtEmail.BackColor = System.Drawing.Color.Transparent;
            this.txtEmail.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtEmail.BackgroundImage")));
            this.txtEmail.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtEmail.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtEmail.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtEmail.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtEmail.BorderRadius = 1;
            this.txtEmail.BorderThickness = 1;
            this.txtEmail.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtEmail.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtEmail.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtEmail.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtEmail.DefaultText = "";
            this.txtEmail.FillColor = System.Drawing.Color.White;
            this.txtEmail.HideSelection = true;
            this.txtEmail.IconLeft = null;
            this.txtEmail.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtEmail.IconPadding = 10;
            this.txtEmail.IconRight = null;
            this.txtEmail.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtEmail.Lines = new string[0];
            this.txtEmail.Location = new System.Drawing.Point(5, 123);
            this.txtEmail.MaxLength = 100;
            this.txtEmail.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtEmail.Modified = false;
            this.txtEmail.Multiline = false;
            this.txtEmail.Name = "txtEmail";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtEmail.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtEmail.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtEmail.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtEmail.OnIdleState = stateProperties12;
            this.txtEmail.Padding = new System.Windows.Forms.Padding(3);
            this.txtEmail.PasswordChar = '\0';
            this.txtEmail.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtEmail.PlaceholderText = "";
            this.txtEmail.ReadOnly = false;
            this.txtEmail.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtEmail.SelectedText = "";
            this.txtEmail.SelectionLength = 0;
            this.txtEmail.SelectionStart = 0;
            this.txtEmail.ShortcutsEnabled = true;
            this.txtEmail.Size = new System.Drawing.Size(336, 39);
            this.txtEmail.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtEmail.TabIndex = 1;
            this.txtEmail.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtEmail.TextMarginBottom = 0;
            this.txtEmail.TextMarginLeft = 3;
            this.txtEmail.TextMarginTop = 1;
            this.txtEmail.TextPlaceholder = "";
            this.txtEmail.UseSystemPasswordChar = false;
            this.txtEmail.WordWrap = true;
            // 
            // txtNome
            // 
            this.txtNome.AcceptsReturn = false;
            this.txtNome.AcceptsTab = false;
            this.txtNome.AnimationSpeed = 200;
            this.txtNome.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtNome.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtNome.AutoSizeHeight = true;
            this.txtNome.BackColor = System.Drawing.Color.Transparent;
            this.txtNome.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtNome.BackgroundImage")));
            this.txtNome.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtNome.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtNome.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtNome.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtNome.BorderRadius = 1;
            this.txtNome.BorderThickness = 1;
            this.txtNome.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtNome.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtNome.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtNome.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtNome.DefaultText = "";
            this.txtNome.FillColor = System.Drawing.Color.White;
            this.txtNome.HideSelection = true;
            this.txtNome.IconLeft = null;
            this.txtNome.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtNome.IconPadding = 10;
            this.txtNome.IconRight = null;
            this.txtNome.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtNome.Lines = new string[0];
            this.txtNome.Location = new System.Drawing.Point(5, 55);
            this.txtNome.MaxLength = 20;
            this.txtNome.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtNome.Modified = false;
            this.txtNome.Multiline = false;
            this.txtNome.Name = "txtNome";
            stateProperties13.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtNome.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtNome.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtNome.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtNome.OnIdleState = stateProperties16;
            this.txtNome.Padding = new System.Windows.Forms.Padding(3);
            this.txtNome.PasswordChar = '\0';
            this.txtNome.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtNome.PlaceholderText = "";
            this.txtNome.ReadOnly = false;
            this.txtNome.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtNome.SelectedText = "";
            this.txtNome.SelectionLength = 0;
            this.txtNome.SelectionStart = 0;
            this.txtNome.ShortcutsEnabled = true;
            this.txtNome.Size = new System.Drawing.Size(331, 39);
            this.txtNome.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtNome.TabIndex = 0;
            this.txtNome.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtNome.TextMarginBottom = 0;
            this.txtNome.TextMarginLeft = 3;
            this.txtNome.TextMarginTop = 1;
            this.txtNome.TextPlaceholder = "";
            this.txtNome.UseSystemPasswordChar = false;
            this.txtNome.WordWrap = true;
            // 
            // btSalvar
            // 
            this.btSalvar.AllowAnimations = true;
            this.btSalvar.AllowMouseEffects = true;
            this.btSalvar.AllowToggling = true;
            this.btSalvar.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.btSalvar.AnimationSpeed = 200;
            this.btSalvar.AutoGenerateColors = false;
            this.btSalvar.AutoRoundBorders = true;
            this.btSalvar.AutoSizeLeftIcon = true;
            this.btSalvar.AutoSizeRightIcon = true;
            this.btSalvar.BackColor = System.Drawing.Color.Transparent;
            this.btSalvar.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btSalvar.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btSalvar.BackgroundImage")));
            this.btSalvar.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btSalvar.ButtonText = "Salvar";
            this.btSalvar.ButtonTextMarginLeft = 0;
            this.btSalvar.ColorContrastOnClick = 45;
            this.btSalvar.ColorContrastOnHover = 45;
            this.btSalvar.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.btSalvar.CustomizableEdges = borderEdges1;
            this.btSalvar.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btSalvar.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btSalvar.DisabledFillColor = System.Drawing.Color.Empty;
            this.btSalvar.DisabledForecolor = System.Drawing.Color.Empty;
            this.btSalvar.Enabled = false;
            this.btSalvar.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btSalvar.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btSalvar.ForeColor = System.Drawing.Color.White;
            this.btSalvar.IconLeft = null;
            this.btSalvar.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btSalvar.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btSalvar.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btSalvar.IconMarginLeft = 11;
            this.btSalvar.IconPadding = 10;
            this.btSalvar.IconRight = null;
            this.btSalvar.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btSalvar.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btSalvar.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btSalvar.IconSize = 25;
            this.btSalvar.IdleBorderColor = System.Drawing.Color.Empty;
            this.btSalvar.IdleBorderRadius = 0;
            this.btSalvar.IdleBorderThickness = 0;
            this.btSalvar.IdleFillColor = System.Drawing.Color.Empty;
            this.btSalvar.IdleIconLeftImage = null;
            this.btSalvar.IdleIconRightImage = null;
            this.btSalvar.IndicateFocus = false;
            this.btSalvar.Location = new System.Drawing.Point(906, 308);
            this.btSalvar.Name = "btSalvar";
            this.btSalvar.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btSalvar.OnDisabledState.BorderRadius = 28;
            this.btSalvar.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btSalvar.OnDisabledState.BorderThickness = 1;
            this.btSalvar.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btSalvar.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btSalvar.OnDisabledState.IconLeftImage = null;
            this.btSalvar.OnDisabledState.IconRightImage = null;
            this.btSalvar.onHoverState.BorderColor = System.Drawing.Color.Green;
            this.btSalvar.onHoverState.BorderRadius = 28;
            this.btSalvar.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btSalvar.onHoverState.BorderThickness = 1;
            this.btSalvar.onHoverState.FillColor = System.Drawing.Color.Green;
            this.btSalvar.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btSalvar.onHoverState.IconLeftImage = null;
            this.btSalvar.onHoverState.IconRightImage = null;
            this.btSalvar.OnIdleState.BorderColor = System.Drawing.Color.Green;
            this.btSalvar.OnIdleState.BorderRadius = 28;
            this.btSalvar.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btSalvar.OnIdleState.BorderThickness = 1;
            this.btSalvar.OnIdleState.FillColor = System.Drawing.Color.Green;
            this.btSalvar.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btSalvar.OnIdleState.IconLeftImage = null;
            this.btSalvar.OnIdleState.IconRightImage = null;
            this.btSalvar.OnPressedState.BorderColor = System.Drawing.Color.SeaGreen;
            this.btSalvar.OnPressedState.BorderRadius = 28;
            this.btSalvar.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btSalvar.OnPressedState.BorderThickness = 1;
            this.btSalvar.OnPressedState.FillColor = System.Drawing.Color.SeaGreen;
            this.btSalvar.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btSalvar.OnPressedState.IconLeftImage = null;
            this.btSalvar.OnPressedState.IconRightImage = null;
            this.btSalvar.Size = new System.Drawing.Size(87, 28);
            this.btSalvar.TabIndex = 2;
            this.btSalvar.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btSalvar.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btSalvar.TextMarginLeft = 0;
            this.btSalvar.TextPadding = new System.Windows.Forms.Padding(0);
            this.btSalvar.UseDefaultRadiusAndThickness = true;
            this.btSalvar.Click += new System.EventHandler(this.btSalvar_Click);
            // 
            // btAtualizar
            // 
            this.btAtualizar.AllowAnimations = true;
            this.btAtualizar.AllowMouseEffects = true;
            this.btAtualizar.AllowToggling = true;
            this.btAtualizar.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.btAtualizar.AnimationSpeed = 200;
            this.btAtualizar.AutoGenerateColors = false;
            this.btAtualizar.AutoRoundBorders = true;
            this.btAtualizar.AutoSizeLeftIcon = true;
            this.btAtualizar.AutoSizeRightIcon = true;
            this.btAtualizar.BackColor = System.Drawing.Color.Transparent;
            this.btAtualizar.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btAtualizar.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btAtualizar.BackgroundImage")));
            this.btAtualizar.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btAtualizar.ButtonText = "Atualizar";
            this.btAtualizar.ButtonTextMarginLeft = 0;
            this.btAtualizar.ColorContrastOnClick = 45;
            this.btAtualizar.ColorContrastOnHover = 45;
            this.btAtualizar.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.btAtualizar.CustomizableEdges = borderEdges2;
            this.btAtualizar.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btAtualizar.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btAtualizar.DisabledFillColor = System.Drawing.Color.Empty;
            this.btAtualizar.DisabledForecolor = System.Drawing.Color.Empty;
            this.btAtualizar.Enabled = false;
            this.btAtualizar.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btAtualizar.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btAtualizar.ForeColor = System.Drawing.Color.White;
            this.btAtualizar.IconLeft = null;
            this.btAtualizar.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btAtualizar.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btAtualizar.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btAtualizar.IconMarginLeft = 11;
            this.btAtualizar.IconPadding = 10;
            this.btAtualizar.IconRight = null;
            this.btAtualizar.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btAtualizar.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btAtualizar.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btAtualizar.IconSize = 25;
            this.btAtualizar.IdleBorderColor = System.Drawing.Color.Empty;
            this.btAtualizar.IdleBorderRadius = 0;
            this.btAtualizar.IdleBorderThickness = 0;
            this.btAtualizar.IdleFillColor = System.Drawing.Color.Empty;
            this.btAtualizar.IdleIconLeftImage = null;
            this.btAtualizar.IdleIconRightImage = null;
            this.btAtualizar.IndicateFocus = false;
            this.btAtualizar.Location = new System.Drawing.Point(768, 364);
            this.btAtualizar.Name = "btAtualizar";
            this.btAtualizar.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btAtualizar.OnDisabledState.BorderRadius = 28;
            this.btAtualizar.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btAtualizar.OnDisabledState.BorderThickness = 1;
            this.btAtualizar.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btAtualizar.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btAtualizar.OnDisabledState.IconLeftImage = null;
            this.btAtualizar.OnDisabledState.IconRightImage = null;
            this.btAtualizar.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btAtualizar.onHoverState.BorderRadius = 28;
            this.btAtualizar.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btAtualizar.onHoverState.BorderThickness = 1;
            this.btAtualizar.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btAtualizar.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btAtualizar.onHoverState.IconLeftImage = null;
            this.btAtualizar.onHoverState.IconRightImage = null;
            this.btAtualizar.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btAtualizar.OnIdleState.BorderRadius = 28;
            this.btAtualizar.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btAtualizar.OnIdleState.BorderThickness = 1;
            this.btAtualizar.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btAtualizar.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btAtualizar.OnIdleState.IconLeftImage = null;
            this.btAtualizar.OnIdleState.IconRightImage = null;
            this.btAtualizar.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btAtualizar.OnPressedState.BorderRadius = 28;
            this.btAtualizar.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btAtualizar.OnPressedState.BorderThickness = 1;
            this.btAtualizar.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btAtualizar.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btAtualizar.OnPressedState.IconLeftImage = null;
            this.btAtualizar.OnPressedState.IconRightImage = null;
            this.btAtualizar.Size = new System.Drawing.Size(87, 28);
            this.btAtualizar.TabIndex = 3;
            this.btAtualizar.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btAtualizar.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btAtualizar.TextMarginLeft = 0;
            this.btAtualizar.TextPadding = new System.Windows.Forms.Padding(0);
            this.btAtualizar.UseDefaultRadiusAndThickness = true;
            this.btAtualizar.Click += new System.EventHandler(this.btAtualizar_Click);
            // 
            // btExcluir
            // 
            this.btExcluir.AllowAnimations = true;
            this.btExcluir.AllowMouseEffects = true;
            this.btExcluir.AllowToggling = true;
            this.btExcluir.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.btExcluir.AnimationSpeed = 200;
            this.btExcluir.AutoGenerateColors = false;
            this.btExcluir.AutoRoundBorders = true;
            this.btExcluir.AutoSizeLeftIcon = true;
            this.btExcluir.AutoSizeRightIcon = true;
            this.btExcluir.BackColor = System.Drawing.Color.Transparent;
            this.btExcluir.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btExcluir.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btExcluir.BackgroundImage")));
            this.btExcluir.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btExcluir.ButtonText = "Excluir";
            this.btExcluir.ButtonTextMarginLeft = 0;
            this.btExcluir.ColorContrastOnClick = 45;
            this.btExcluir.ColorContrastOnHover = 45;
            this.btExcluir.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.btExcluir.CustomizableEdges = borderEdges3;
            this.btExcluir.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btExcluir.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btExcluir.DisabledFillColor = System.Drawing.Color.Empty;
            this.btExcluir.DisabledForecolor = System.Drawing.Color.Empty;
            this.btExcluir.Enabled = false;
            this.btExcluir.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btExcluir.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btExcluir.ForeColor = System.Drawing.Color.White;
            this.btExcluir.IconLeft = null;
            this.btExcluir.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btExcluir.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btExcluir.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btExcluir.IconMarginLeft = 11;
            this.btExcluir.IconPadding = 10;
            this.btExcluir.IconRight = null;
            this.btExcluir.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btExcluir.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btExcluir.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btExcluir.IconSize = 25;
            this.btExcluir.IdleBorderColor = System.Drawing.Color.Empty;
            this.btExcluir.IdleBorderRadius = 0;
            this.btExcluir.IdleBorderThickness = 0;
            this.btExcluir.IdleFillColor = System.Drawing.Color.Empty;
            this.btExcluir.IdleIconLeftImage = null;
            this.btExcluir.IdleIconRightImage = null;
            this.btExcluir.IndicateFocus = false;
            this.btExcluir.Location = new System.Drawing.Point(831, 432);
            this.btExcluir.Name = "btExcluir";
            this.btExcluir.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btExcluir.OnDisabledState.BorderRadius = 28;
            this.btExcluir.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btExcluir.OnDisabledState.BorderThickness = 1;
            this.btExcluir.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btExcluir.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btExcluir.OnDisabledState.IconLeftImage = null;
            this.btExcluir.OnDisabledState.IconRightImage = null;
            this.btExcluir.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.btExcluir.onHoverState.BorderRadius = 28;
            this.btExcluir.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btExcluir.onHoverState.BorderThickness = 1;
            this.btExcluir.onHoverState.FillColor = System.Drawing.Color.Maroon;
            this.btExcluir.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btExcluir.onHoverState.IconLeftImage = null;
            this.btExcluir.onHoverState.IconRightImage = null;
            this.btExcluir.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.btExcluir.OnIdleState.BorderRadius = 28;
            this.btExcluir.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btExcluir.OnIdleState.BorderThickness = 1;
            this.btExcluir.OnIdleState.FillColor = System.Drawing.Color.Maroon;
            this.btExcluir.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btExcluir.OnIdleState.IconLeftImage = null;
            this.btExcluir.OnIdleState.IconRightImage = null;
            this.btExcluir.OnPressedState.BorderColor = System.Drawing.Color.Firebrick;
            this.btExcluir.OnPressedState.BorderRadius = 28;
            this.btExcluir.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btExcluir.OnPressedState.BorderThickness = 1;
            this.btExcluir.OnPressedState.FillColor = System.Drawing.Color.Firebrick;
            this.btExcluir.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btExcluir.OnPressedState.IconLeftImage = null;
            this.btExcluir.OnPressedState.IconRightImage = null;
            this.btExcluir.Size = new System.Drawing.Size(87, 28);
            this.btExcluir.TabIndex = 4;
            this.btExcluir.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btExcluir.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btExcluir.TextMarginLeft = 0;
            this.btExcluir.TextPadding = new System.Windows.Forms.Padding(0);
            this.btExcluir.UseDefaultRadiusAndThickness = true;
            this.btExcluir.Click += new System.EventHandler(this.btExcluir_Click);
            // 
            // btNovo
            // 
            this.btNovo.AllowAnimations = true;
            this.btNovo.AllowMouseEffects = true;
            this.btNovo.AllowToggling = true;
            this.btNovo.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.btNovo.AnimationSpeed = 200;
            this.btNovo.AutoGenerateColors = false;
            this.btNovo.AutoRoundBorders = true;
            this.btNovo.AutoSizeLeftIcon = true;
            this.btNovo.AutoSizeRightIcon = true;
            this.btNovo.BackColor = System.Drawing.Color.Transparent;
            this.btNovo.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btNovo.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btNovo.BackgroundImage")));
            this.btNovo.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btNovo.ButtonText = "Novo/Editar";
            this.btNovo.ButtonTextMarginLeft = 0;
            this.btNovo.ColorContrastOnClick = 45;
            this.btNovo.ColorContrastOnHover = 45;
            this.btNovo.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.btNovo.CustomizableEdges = borderEdges4;
            this.btNovo.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btNovo.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btNovo.DisabledFillColor = System.Drawing.Color.Empty;
            this.btNovo.DisabledForecolor = System.Drawing.Color.Empty;
            this.btNovo.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btNovo.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btNovo.ForeColor = System.Drawing.Color.White;
            this.btNovo.IconLeft = null;
            this.btNovo.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btNovo.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btNovo.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btNovo.IconMarginLeft = 11;
            this.btNovo.IconPadding = 10;
            this.btNovo.IconRight = null;
            this.btNovo.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btNovo.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btNovo.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btNovo.IconSize = 25;
            this.btNovo.IdleBorderColor = System.Drawing.Color.Empty;
            this.btNovo.IdleBorderRadius = 0;
            this.btNovo.IdleBorderThickness = 0;
            this.btNovo.IdleFillColor = System.Drawing.Color.Empty;
            this.btNovo.IdleIconLeftImage = null;
            this.btNovo.IdleIconRightImage = null;
            this.btNovo.IndicateFocus = false;
            this.btNovo.Location = new System.Drawing.Point(768, 308);
            this.btNovo.Name = "btNovo";
            this.btNovo.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btNovo.OnDisabledState.BorderRadius = 28;
            this.btNovo.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btNovo.OnDisabledState.BorderThickness = 1;
            this.btNovo.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btNovo.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btNovo.OnDisabledState.IconLeftImage = null;
            this.btNovo.OnDisabledState.IconRightImage = null;
            this.btNovo.onHoverState.BorderColor = System.Drawing.Color.Orange;
            this.btNovo.onHoverState.BorderRadius = 28;
            this.btNovo.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btNovo.onHoverState.BorderThickness = 1;
            this.btNovo.onHoverState.FillColor = System.Drawing.Color.Orange;
            this.btNovo.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btNovo.onHoverState.IconLeftImage = null;
            this.btNovo.onHoverState.IconRightImage = null;
            this.btNovo.OnIdleState.BorderColor = System.Drawing.Color.Orange;
            this.btNovo.OnIdleState.BorderRadius = 28;
            this.btNovo.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btNovo.OnIdleState.BorderThickness = 1;
            this.btNovo.OnIdleState.FillColor = System.Drawing.Color.Orange;
            this.btNovo.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btNovo.OnIdleState.IconLeftImage = null;
            this.btNovo.OnIdleState.IconRightImage = null;
            this.btNovo.OnPressedState.BorderColor = System.Drawing.Color.Gold;
            this.btNovo.OnPressedState.BorderRadius = 28;
            this.btNovo.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btNovo.OnPressedState.BorderThickness = 1;
            this.btNovo.OnPressedState.FillColor = System.Drawing.Color.Gold;
            this.btNovo.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btNovo.OnPressedState.IconLeftImage = null;
            this.btNovo.OnPressedState.IconRightImage = null;
            this.btNovo.Size = new System.Drawing.Size(87, 28);
            this.btNovo.TabIndex = 5;
            this.btNovo.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btNovo.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btNovo.TextMarginLeft = 0;
            this.btNovo.TextPadding = new System.Windows.Forms.Padding(0);
            this.btNovo.UseDefaultRadiusAndThickness = true;
            this.btNovo.Click += new System.EventHandler(this.btNovo_Click);
            // 
            // btDesbloquear
            // 
            this.btDesbloquear.AllowAnimations = true;
            this.btDesbloquear.AllowMouseEffects = true;
            this.btDesbloquear.AllowToggling = true;
            this.btDesbloquear.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.btDesbloquear.AnimationSpeed = 200;
            this.btDesbloquear.AutoGenerateColors = false;
            this.btDesbloquear.AutoRoundBorders = true;
            this.btDesbloquear.AutoSizeLeftIcon = true;
            this.btDesbloquear.AutoSizeRightIcon = true;
            this.btDesbloquear.BackColor = System.Drawing.Color.Transparent;
            this.btDesbloquear.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btDesbloquear.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btDesbloquear.BackgroundImage")));
            this.btDesbloquear.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btDesbloquear.ButtonText = "Desbloquear";
            this.btDesbloquear.ButtonTextMarginLeft = 0;
            this.btDesbloquear.ColorContrastOnClick = 45;
            this.btDesbloquear.ColorContrastOnHover = 45;
            this.btDesbloquear.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.btDesbloquear.CustomizableEdges = borderEdges5;
            this.btDesbloquear.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btDesbloquear.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btDesbloquear.DisabledFillColor = System.Drawing.Color.Empty;
            this.btDesbloquear.DisabledForecolor = System.Drawing.Color.Empty;
            this.btDesbloquear.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btDesbloquear.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btDesbloquear.ForeColor = System.Drawing.Color.White;
            this.btDesbloquear.IconLeft = null;
            this.btDesbloquear.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btDesbloquear.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btDesbloquear.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btDesbloquear.IconMarginLeft = 11;
            this.btDesbloquear.IconPadding = 10;
            this.btDesbloquear.IconRight = null;
            this.btDesbloquear.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btDesbloquear.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btDesbloquear.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btDesbloquear.IconSize = 25;
            this.btDesbloquear.IdleBorderColor = System.Drawing.Color.Empty;
            this.btDesbloquear.IdleBorderRadius = 0;
            this.btDesbloquear.IdleBorderThickness = 0;
            this.btDesbloquear.IdleFillColor = System.Drawing.Color.Empty;
            this.btDesbloquear.IdleIconLeftImage = null;
            this.btDesbloquear.IdleIconRightImage = null;
            this.btDesbloquear.IndicateFocus = false;
            this.btDesbloquear.Location = new System.Drawing.Point(906, 364);
            this.btDesbloquear.Name = "btDesbloquear";
            this.btDesbloquear.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btDesbloquear.OnDisabledState.BorderRadius = 28;
            this.btDesbloquear.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btDesbloquear.OnDisabledState.BorderThickness = 1;
            this.btDesbloquear.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btDesbloquear.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btDesbloquear.OnDisabledState.IconLeftImage = null;
            this.btDesbloquear.OnDisabledState.IconRightImage = null;
            this.btDesbloquear.onHoverState.BorderColor = System.Drawing.Color.DarkViolet;
            this.btDesbloquear.onHoverState.BorderRadius = 28;
            this.btDesbloquear.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btDesbloquear.onHoverState.BorderThickness = 1;
            this.btDesbloquear.onHoverState.FillColor = System.Drawing.Color.DarkViolet;
            this.btDesbloquear.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btDesbloquear.onHoverState.IconLeftImage = null;
            this.btDesbloquear.onHoverState.IconRightImage = null;
            this.btDesbloquear.OnIdleState.BorderColor = System.Drawing.Color.DarkViolet;
            this.btDesbloquear.OnIdleState.BorderRadius = 28;
            this.btDesbloquear.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btDesbloquear.OnIdleState.BorderThickness = 1;
            this.btDesbloquear.OnIdleState.FillColor = System.Drawing.Color.DarkViolet;
            this.btDesbloquear.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btDesbloquear.OnIdleState.IconLeftImage = null;
            this.btDesbloquear.OnIdleState.IconRightImage = null;
            this.btDesbloquear.OnPressedState.BorderColor = System.Drawing.Color.Indigo;
            this.btDesbloquear.OnPressedState.BorderRadius = 28;
            this.btDesbloquear.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btDesbloquear.OnPressedState.BorderThickness = 1;
            this.btDesbloquear.OnPressedState.FillColor = System.Drawing.Color.Indigo;
            this.btDesbloquear.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btDesbloquear.OnPressedState.IconLeftImage = null;
            this.btDesbloquear.OnPressedState.IconRightImage = null;
            this.btDesbloquear.Size = new System.Drawing.Size(87, 28);
            this.btDesbloquear.TabIndex = 6;
            this.btDesbloquear.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btDesbloquear.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btDesbloquear.TextMarginLeft = 0;
            this.btDesbloquear.TextPadding = new System.Windows.Forms.Padding(0);
            this.btDesbloquear.UseDefaultRadiusAndThickness = true;
            this.btDesbloquear.Click += new System.EventHandler(this.btDesbloquear_Click);
            // 
            // Usuariosfrm
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.WhiteSmoke;
            this.ClientSize = new System.Drawing.Size(1005, 545);
            this.ControlBox = false;
            this.Controls.Add(this.btDesbloquear);
            this.Controls.Add(this.btNovo);
            this.Controls.Add(this.btExcluir);
            this.Controls.Add(this.btAtualizar);
            this.Controls.Add(this.btSalvar);
            this.Controls.Add(this.radGroupBox1);
            this.Controls.Add(this.GridUsuarios);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.MaximizeBox = false;
            this.MinimizeBox = false;
            this.Name = "Usuariosfrm";
            this.ShowIcon = false;
            this.ShowInTaskbar = false;
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterParent;
            this.Load += new System.EventHandler(this.Usuariosfrm_Load);
            ((System.ComponentModel.ISupportInitialize)(this.GridUsuarios)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.radGroupBox1)).EndInit();
            this.radGroupBox1.ResumeLayout(false);
            this.radGroupBox1.PerformLayout();
            this.ResumeLayout(false);

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuDataGridView GridUsuarios;
        private Telerik.WinControls.UI.RadGroupBox radGroupBox1;
        private Telerik.WinControls.Themes.AquaTheme aquaTheme1;
        private Bunifu.UI.WinForms.BunifuTextBox txtNome;
        private Bunifu.UI.WinForms.BunifuTextBox txtSenha;
        private Bunifu.UI.WinForms.BunifuTextBox txtEmail;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
        private Bunifu.UI.WinForms.BunifuCheckBox chkAtivo;
        private System.Windows.Forms.ComboBox cbCargo;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel2;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel3;
        private System.Windows.Forms.ComboBox cbNivel;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel4;
        private Bunifu.UI.WinForms.BunifuTextBox txtData;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel7;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel6;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel5;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btSalvar;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btAtualizar;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btExcluir;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btNovo;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btDesbloquear;
    }
}