namespace Acessos
{
    partial class Geral
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Geral));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges7 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges8 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            this.aquaTheme1 = new Telerik.WinControls.Themes.AquaTheme();
            this.materialTheme1 = new Telerik.WinControls.Themes.MaterialTheme();
            this.radFormConverter1 = new Telerik.WinControls.UI.RadFormConverter();
            this.lbusuario = new Bunifu.UI.WinForms.BunifuLabel();
            this.pictureBox1 = new System.Windows.Forms.PictureBox();
            this.gb1 = new Telerik.WinControls.UI.RadGroupBox();
            this.lbMsg = new Bunifu.UI.WinForms.BunifuLabel();
            this.bt4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.bt3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.bt2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.bt1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.btLogout = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.toolTip1 = new System.Windows.Forms.ToolTip(this.components);
            this.radGroupBox1 = new Telerik.WinControls.UI.RadGroupBox();
            this.ItensPromo = new Bunifu.UI.WinForms.BunifuLabel();
            this.ItensVencendo = new Bunifu.UI.WinForms.BunifuLabel();
            this.OrcNo = new Bunifu.UI.WinForms.BunifuLabel();
            this.ValorEstq = new Bunifu.UI.WinForms.BunifuLabel();
            this.OrcYes = new Bunifu.UI.WinForms.BunifuLabel();
            this.OrcEspera = new Bunifu.UI.WinForms.BunifuLabel();
            this.TotalGast = new Bunifu.UI.WinForms.BunifuLabel();
            this.TotalVendasHj = new Bunifu.UI.WinForms.BunifuLabel();
            this.QuantClienAt = new Bunifu.UI.WinForms.BunifuLabel();
            this.QuantForn = new Bunifu.UI.WinForms.BunifuLabel();
            this.ProdEstoq = new Bunifu.UI.WinForms.BunifuLabel();
            this.radGroupBox2 = new Telerik.WinControls.UI.RadGroupBox();
            this.lbMsg2 = new Bunifu.UI.WinForms.BunifuLabel();
            this.btVendas = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.btOrcamentos = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.btAprovarOrcamentos = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.lblStatus = new Bunifu.UI.WinForms.BunifuLabel();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.gb1)).BeginInit();
            this.gb1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.radGroupBox1)).BeginInit();
            this.radGroupBox1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.radGroupBox2)).BeginInit();
            this.radGroupBox2.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this)).BeginInit();
            this.SuspendLayout();
            // 
            // lbusuario
            // 
            this.lbusuario.AllowParentOverrides = false;
            this.lbusuario.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.lbusuario.AutoEllipsis = false;
            this.lbusuario.CursorType = null;
            this.lbusuario.Font = new System.Drawing.Font("Segoe UI Semibold", 10F, System.Drawing.FontStyle.Bold);
            this.lbusuario.ForeColor = System.Drawing.Color.DarkCyan;
            this.lbusuario.Location = new System.Drawing.Point(40, 703);
            this.lbusuario.Name = "lbusuario";
            this.lbusuario.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.lbusuario.Size = new System.Drawing.Size(91, 17);
            this.lbusuario.TabIndex = 0;
            this.lbusuario.Text = "usuario logado";
            this.lbusuario.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.lbusuario.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // pictureBox1
            // 
            this.pictureBox1.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.pictureBox1.BackColor = System.Drawing.Color.Transparent;
            this.pictureBox1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Zoom;
            this.pictureBox1.ErrorImage = null;
            this.pictureBox1.Image = ((System.Drawing.Image)(resources.GetObject("pictureBox1.Image")));
            this.pictureBox1.InitialImage = null;
            this.pictureBox1.Location = new System.Drawing.Point(0, 692);
            this.pictureBox1.Margin = new System.Windows.Forms.Padding(1);
            this.pictureBox1.Name = "pictureBox1";
            this.pictureBox1.Size = new System.Drawing.Size(34, 34);
            this.pictureBox1.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.pictureBox1.TabIndex = 1;
            this.pictureBox1.TabStop = false;
            // 
            // gb1
            // 
            this.gb1.AccessibleRole = System.Windows.Forms.AccessibleRole.Grouping;
            this.gb1.BackColor = System.Drawing.Color.WhiteSmoke;
            this.gb1.Controls.Add(this.lbMsg);
            this.gb1.Controls.Add(this.bt4);
            this.gb1.Controls.Add(this.bt3);
            this.gb1.Controls.Add(this.bt2);
            this.gb1.Controls.Add(this.bt1);
            this.gb1.HeaderAlignment = Telerik.WinControls.UI.HeaderAlignment.Center;
            this.gb1.HeaderText = "Administrativo";
            this.gb1.Location = new System.Drawing.Point(12, 12);
            this.gb1.Name = "gb1";
            this.gb1.Size = new System.Drawing.Size(606, 153);
            this.gb1.TabIndex = 2;
            this.gb1.Text = "Administrativo";
            this.gb1.ThemeName = "Aqua";
            // 
            // lbMsg
            // 
            this.lbMsg.AllowParentOverrides = false;
            this.lbMsg.AutoEllipsis = false;
            this.lbMsg.AutoSize = false;
            this.lbMsg.Cursor = System.Windows.Forms.Cursors.Default;
            this.lbMsg.CursorType = System.Windows.Forms.Cursors.Default;
            this.lbMsg.Font = new System.Drawing.Font("Yu Gothic UI", 12F, ((System.Drawing.FontStyle)((System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Italic))));
            this.lbMsg.ForeColor = System.Drawing.SystemColors.MenuHighlight;
            this.lbMsg.Location = new System.Drawing.Point(28, 121);
            this.lbMsg.Name = "lbMsg";
            this.lbMsg.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.lbMsg.Size = new System.Drawing.Size(555, 27);
            this.lbMsg.TabIndex = 7;
            this.lbMsg.Text = "Mensagem";
            this.lbMsg.TextAlignment = System.Drawing.ContentAlignment.MiddleCenter;
            this.lbMsg.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.lbMsg.Visible = false;
            // 
            // bt4
            // 
            this.bt4.AllowAnimations = true;
            this.bt4.AllowMouseEffects = true;
            this.bt4.AllowToggling = true;
            this.bt4.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.bt4.AnimationSpeed = 200;
            this.bt4.AutoGenerateColors = false;
            this.bt4.AutoRoundBorders = true;
            this.bt4.AutoSizeLeftIcon = true;
            this.bt4.AutoSizeRightIcon = true;
            this.bt4.BackColor = System.Drawing.Color.Transparent;
            this.bt4.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.bt4.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bt4.BackgroundImage")));
            this.bt4.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bt4.ButtonText = "";
            this.bt4.ButtonTextMarginLeft = 0;
            this.bt4.ColorContrastOnClick = 45;
            this.bt4.ColorContrastOnHover = 45;
            this.bt4.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.bt4.CustomizableEdges = borderEdges1;
            this.bt4.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bt4.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bt4.DisabledFillColor = System.Drawing.Color.Empty;
            this.bt4.DisabledForecolor = System.Drawing.Color.Empty;
            this.bt4.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.bt4.Font = new System.Drawing.Font("Book Antiqua", 14.25F, ((System.Drawing.FontStyle)((System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Italic))), System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bt4.ForeColor = System.Drawing.Color.Teal;
            this.bt4.IconLeft = ((System.Drawing.Image)(resources.GetObject("bt4.IconLeft")));
            this.bt4.IconLeftAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bt4.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bt4.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bt4.IconMarginLeft = 11;
            this.bt4.IconPadding = 10;
            this.bt4.IconRight = null;
            this.bt4.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bt4.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bt4.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bt4.IconSize = 25;
            this.bt4.IdleBorderColor = System.Drawing.Color.Empty;
            this.bt4.IdleBorderRadius = 0;
            this.bt4.IdleBorderThickness = 0;
            this.bt4.IdleFillColor = System.Drawing.Color.Empty;
            this.bt4.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("bt4.IdleIconLeftImage")));
            this.bt4.IdleIconRightImage = null;
            this.bt4.IndicateFocus = true;
            this.bt4.Location = new System.Drawing.Point(407, 33);
            this.bt4.Name = "bt4";
            this.bt4.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bt4.OnDisabledState.BorderRadius = 82;
            this.bt4.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bt4.OnDisabledState.BorderThickness = 1;
            this.bt4.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bt4.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bt4.OnDisabledState.IconLeftImage = null;
            this.bt4.OnDisabledState.IconRightImage = null;
            this.bt4.onHoverState.BorderColor = System.Drawing.Color.Transparent;
            this.bt4.onHoverState.BorderRadius = 82;
            this.bt4.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bt4.onHoverState.BorderThickness = 1;
            this.bt4.onHoverState.FillColor = System.Drawing.Color.Transparent;
            this.bt4.onHoverState.ForeColor = System.Drawing.Color.DodgerBlue;
            this.bt4.onHoverState.IconLeftImage = null;
            this.bt4.onHoverState.IconRightImage = null;
            this.bt4.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.bt4.OnIdleState.BorderRadius = 82;
            this.bt4.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bt4.OnIdleState.BorderThickness = 1;
            this.bt4.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.bt4.OnIdleState.ForeColor = System.Drawing.Color.Teal;
            this.bt4.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("bt4.OnIdleState.IconLeftImage")));
            this.bt4.OnIdleState.IconRightImage = null;
            this.bt4.OnPressedState.BorderColor = System.Drawing.Color.Transparent;
            this.bt4.OnPressedState.BorderRadius = 82;
            this.bt4.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bt4.OnPressedState.BorderThickness = 1;
            this.bt4.OnPressedState.FillColor = System.Drawing.Color.Transparent;
            this.bt4.OnPressedState.ForeColor = System.Drawing.Color.DimGray;
            this.bt4.OnPressedState.IconLeftImage = null;
            this.bt4.OnPressedState.IconRightImage = null;
            this.bt4.Size = new System.Drawing.Size(99, 82);
            this.bt4.TabIndex = 4;
            this.bt4.TabStop = false;
            this.bt4.TextAlign = System.Drawing.ContentAlignment.BottomCenter;
            this.bt4.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bt4.TextMarginLeft = 0;
            this.bt4.TextPadding = new System.Windows.Forms.Padding(0);
            this.bt4.UseDefaultRadiusAndThickness = true;
            this.bt4.Click += new System.EventHandler(this.btClientes_Click);
            // 
            // bt3
            // 
            this.bt3.AllowAnimations = true;
            this.bt3.AllowMouseEffects = true;
            this.bt3.AllowToggling = true;
            this.bt3.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.bt3.AnimationSpeed = 200;
            this.bt3.AutoGenerateColors = false;
            this.bt3.AutoRoundBorders = true;
            this.bt3.AutoSizeLeftIcon = true;
            this.bt3.AutoSizeRightIcon = true;
            this.bt3.BackColor = System.Drawing.Color.Transparent;
            this.bt3.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.bt3.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bt3.BackgroundImage")));
            this.bt3.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bt3.ButtonText = "";
            this.bt3.ButtonTextMarginLeft = 0;
            this.bt3.ColorContrastOnClick = 45;
            this.bt3.ColorContrastOnHover = 45;
            this.bt3.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.bt3.CustomizableEdges = borderEdges2;
            this.bt3.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bt3.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bt3.DisabledFillColor = System.Drawing.Color.Empty;
            this.bt3.DisabledForecolor = System.Drawing.Color.Empty;
            this.bt3.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.bt3.Font = new System.Drawing.Font("Book Antiqua", 14.25F, ((System.Drawing.FontStyle)((System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Italic))), System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bt3.ForeColor = System.Drawing.Color.Teal;
            this.bt3.IconLeft = ((System.Drawing.Image)(resources.GetObject("bt3.IconLeft")));
            this.bt3.IconLeftAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bt3.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bt3.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bt3.IconMarginLeft = 11;
            this.bt3.IconPadding = 10;
            this.bt3.IconRight = null;
            this.bt3.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bt3.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bt3.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bt3.IconSize = 25;
            this.bt3.IdleBorderColor = System.Drawing.Color.Empty;
            this.bt3.IdleBorderRadius = 0;
            this.bt3.IdleBorderThickness = 0;
            this.bt3.IdleFillColor = System.Drawing.Color.Empty;
            this.bt3.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("bt3.IdleIconLeftImage")));
            this.bt3.IdleIconRightImage = null;
            this.bt3.IndicateFocus = true;
            this.bt3.Location = new System.Drawing.Point(302, 33);
            this.bt3.Name = "bt3";
            this.bt3.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bt3.OnDisabledState.BorderRadius = 82;
            this.bt3.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bt3.OnDisabledState.BorderThickness = 1;
            this.bt3.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bt3.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bt3.OnDisabledState.IconLeftImage = null;
            this.bt3.OnDisabledState.IconRightImage = null;
            this.bt3.onHoverState.BorderColor = System.Drawing.Color.Transparent;
            this.bt3.onHoverState.BorderRadius = 82;
            this.bt3.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bt3.onHoverState.BorderThickness = 1;
            this.bt3.onHoverState.FillColor = System.Drawing.Color.Transparent;
            this.bt3.onHoverState.ForeColor = System.Drawing.Color.DodgerBlue;
            this.bt3.onHoverState.IconLeftImage = null;
            this.bt3.onHoverState.IconRightImage = null;
            this.bt3.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.bt3.OnIdleState.BorderRadius = 82;
            this.bt3.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bt3.OnIdleState.BorderThickness = 1;
            this.bt3.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.bt3.OnIdleState.ForeColor = System.Drawing.Color.Teal;
            this.bt3.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("bt3.OnIdleState.IconLeftImage")));
            this.bt3.OnIdleState.IconRightImage = null;
            this.bt3.OnPressedState.BorderColor = System.Drawing.Color.Transparent;
            this.bt3.OnPressedState.BorderRadius = 82;
            this.bt3.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bt3.OnPressedState.BorderThickness = 1;
            this.bt3.OnPressedState.FillColor = System.Drawing.Color.Transparent;
            this.bt3.OnPressedState.ForeColor = System.Drawing.Color.DimGray;
            this.bt3.OnPressedState.IconLeftImage = null;
            this.bt3.OnPressedState.IconRightImage = null;
            this.bt3.Size = new System.Drawing.Size(99, 82);
            this.bt3.TabIndex = 6;
            this.bt3.TabStop = false;
            this.bt3.TextAlign = System.Drawing.ContentAlignment.BottomCenter;
            this.bt3.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bt3.TextMarginLeft = 0;
            this.bt3.TextPadding = new System.Windows.Forms.Padding(0);
            this.bt3.UseDefaultRadiusAndThickness = true;
            this.bt3.Click += new System.EventHandler(this.btFornecedores_Click);
            // 
            // bt2
            // 
            this.bt2.AllowAnimations = true;
            this.bt2.AllowMouseEffects = true;
            this.bt2.AllowToggling = true;
            this.bt2.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.bt2.AnimationSpeed = 200;
            this.bt2.AutoGenerateColors = false;
            this.bt2.AutoRoundBorders = true;
            this.bt2.AutoSizeLeftIcon = true;
            this.bt2.AutoSizeRightIcon = true;
            this.bt2.BackColor = System.Drawing.Color.Transparent;
            this.bt2.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.bt2.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bt2.BackgroundImage")));
            this.bt2.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bt2.ButtonText = "";
            this.bt2.ButtonTextMarginLeft = 0;
            this.bt2.ColorContrastOnClick = 45;
            this.bt2.ColorContrastOnHover = 45;
            this.bt2.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.bt2.CustomizableEdges = borderEdges3;
            this.bt2.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bt2.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bt2.DisabledFillColor = System.Drawing.Color.Empty;
            this.bt2.DisabledForecolor = System.Drawing.Color.Empty;
            this.bt2.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.bt2.Font = new System.Drawing.Font("Book Antiqua", 14.25F, ((System.Drawing.FontStyle)((System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Italic))), System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bt2.ForeColor = System.Drawing.Color.Teal;
            this.bt2.IconLeft = ((System.Drawing.Image)(resources.GetObject("bt2.IconLeft")));
            this.bt2.IconLeftAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bt2.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bt2.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bt2.IconMarginLeft = 11;
            this.bt2.IconPadding = 10;
            this.bt2.IconRight = null;
            this.bt2.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bt2.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bt2.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bt2.IconSize = 25;
            this.bt2.IdleBorderColor = System.Drawing.Color.Empty;
            this.bt2.IdleBorderRadius = 0;
            this.bt2.IdleBorderThickness = 0;
            this.bt2.IdleFillColor = System.Drawing.Color.Empty;
            this.bt2.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("bt2.IdleIconLeftImage")));
            this.bt2.IdleIconRightImage = null;
            this.bt2.IndicateFocus = true;
            this.bt2.Location = new System.Drawing.Point(177, 33);
            this.bt2.Name = "bt2";
            this.bt2.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bt2.OnDisabledState.BorderRadius = 82;
            this.bt2.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bt2.OnDisabledState.BorderThickness = 1;
            this.bt2.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bt2.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bt2.OnDisabledState.IconLeftImage = null;
            this.bt2.OnDisabledState.IconRightImage = null;
            this.bt2.onHoverState.BorderColor = System.Drawing.Color.Transparent;
            this.bt2.onHoverState.BorderRadius = 82;
            this.bt2.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bt2.onHoverState.BorderThickness = 1;
            this.bt2.onHoverState.FillColor = System.Drawing.Color.Transparent;
            this.bt2.onHoverState.ForeColor = System.Drawing.Color.DodgerBlue;
            this.bt2.onHoverState.IconLeftImage = null;
            this.bt2.onHoverState.IconRightImage = null;
            this.bt2.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.bt2.OnIdleState.BorderRadius = 82;
            this.bt2.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bt2.OnIdleState.BorderThickness = 1;
            this.bt2.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.bt2.OnIdleState.ForeColor = System.Drawing.Color.Teal;
            this.bt2.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("bt2.OnIdleState.IconLeftImage")));
            this.bt2.OnIdleState.IconRightImage = null;
            this.bt2.OnPressedState.BorderColor = System.Drawing.Color.Transparent;
            this.bt2.OnPressedState.BorderRadius = 82;
            this.bt2.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bt2.OnPressedState.BorderThickness = 1;
            this.bt2.OnPressedState.FillColor = System.Drawing.Color.Transparent;
            this.bt2.OnPressedState.ForeColor = System.Drawing.Color.DimGray;
            this.bt2.OnPressedState.IconLeftImage = null;
            this.bt2.OnPressedState.IconRightImage = null;
            this.bt2.Size = new System.Drawing.Size(99, 82);
            this.bt2.TabIndex = 5;
            this.bt2.TabStop = false;
            this.bt2.TextAlign = System.Drawing.ContentAlignment.BottomCenter;
            this.bt2.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bt2.TextMarginLeft = 0;
            this.bt2.TextPadding = new System.Windows.Forms.Padding(0);
            this.bt2.UseDefaultRadiusAndThickness = true;
            this.bt2.Click += new System.EventHandler(this.btProdutos_Click);
            // 
            // bt1
            // 
            this.bt1.AllowAnimations = true;
            this.bt1.AllowMouseEffects = true;
            this.bt1.AllowToggling = true;
            this.bt1.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.bt1.AnimationSpeed = 200;
            this.bt1.AutoGenerateColors = false;
            this.bt1.AutoRoundBorders = true;
            this.bt1.AutoSizeLeftIcon = true;
            this.bt1.AutoSizeRightIcon = true;
            this.bt1.BackColor = System.Drawing.Color.Transparent;
            this.bt1.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.bt1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bt1.BackgroundImage")));
            this.bt1.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bt1.ButtonText = "";
            this.bt1.ButtonTextMarginLeft = 0;
            this.bt1.ColorContrastOnClick = 45;
            this.bt1.ColorContrastOnHover = 45;
            this.bt1.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.bt1.CustomizableEdges = borderEdges4;
            this.bt1.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bt1.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bt1.DisabledFillColor = System.Drawing.Color.Empty;
            this.bt1.DisabledForecolor = System.Drawing.Color.Empty;
            this.bt1.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.bt1.Font = new System.Drawing.Font("Book Antiqua", 14.25F, ((System.Drawing.FontStyle)((System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Italic))), System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bt1.ForeColor = System.Drawing.Color.Teal;
            this.bt1.IconLeft = ((System.Drawing.Image)(resources.GetObject("bt1.IconLeft")));
            this.bt1.IconLeftAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bt1.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bt1.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bt1.IconMarginLeft = 11;
            this.bt1.IconPadding = 10;
            this.bt1.IconRight = null;
            this.bt1.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bt1.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bt1.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bt1.IconSize = 25;
            this.bt1.IdleBorderColor = System.Drawing.Color.Empty;
            this.bt1.IdleBorderRadius = 0;
            this.bt1.IdleBorderThickness = 0;
            this.bt1.IdleFillColor = System.Drawing.Color.Empty;
            this.bt1.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("bt1.IdleIconLeftImage")));
            this.bt1.IdleIconRightImage = null;
            this.bt1.IndicateFocus = true;
            this.bt1.Location = new System.Drawing.Point(60, 33);
            this.bt1.Name = "bt1";
            this.bt1.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bt1.OnDisabledState.BorderRadius = 82;
            this.bt1.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bt1.OnDisabledState.BorderThickness = 1;
            this.bt1.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bt1.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bt1.OnDisabledState.IconLeftImage = null;
            this.bt1.OnDisabledState.IconRightImage = null;
            this.bt1.onHoverState.BorderColor = System.Drawing.Color.Transparent;
            this.bt1.onHoverState.BorderRadius = 82;
            this.bt1.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bt1.onHoverState.BorderThickness = 1;
            this.bt1.onHoverState.FillColor = System.Drawing.Color.Transparent;
            this.bt1.onHoverState.ForeColor = System.Drawing.Color.DodgerBlue;
            this.bt1.onHoverState.IconLeftImage = null;
            this.bt1.onHoverState.IconRightImage = null;
            this.bt1.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.bt1.OnIdleState.BorderRadius = 82;
            this.bt1.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bt1.OnIdleState.BorderThickness = 1;
            this.bt1.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.bt1.OnIdleState.ForeColor = System.Drawing.Color.Teal;
            this.bt1.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("bt1.OnIdleState.IconLeftImage")));
            this.bt1.OnIdleState.IconRightImage = null;
            this.bt1.OnPressedState.BorderColor = System.Drawing.Color.Transparent;
            this.bt1.OnPressedState.BorderRadius = 82;
            this.bt1.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bt1.OnPressedState.BorderThickness = 1;
            this.bt1.OnPressedState.FillColor = System.Drawing.Color.Transparent;
            this.bt1.OnPressedState.ForeColor = System.Drawing.Color.DimGray;
            this.bt1.OnPressedState.IconLeftImage = null;
            this.bt1.OnPressedState.IconRightImage = null;
            this.bt1.Size = new System.Drawing.Size(99, 82);
            this.bt1.TabIndex = 4;
            this.bt1.TabStop = false;
            this.bt1.TextAlign = System.Drawing.ContentAlignment.BottomCenter;
            this.bt1.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bt1.TextMarginLeft = 0;
            this.bt1.TextPadding = new System.Windows.Forms.Padding(0);
            this.bt1.UseDefaultRadiusAndThickness = true;
            this.bt1.Click += new System.EventHandler(this.btUsuarios_Click);
            // 
            // btLogout
            // 
            this.btLogout.AllowAnimations = true;
            this.btLogout.AllowMouseEffects = true;
            this.btLogout.AllowToggling = true;
            this.btLogout.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.btLogout.AnimationSpeed = 200;
            this.btLogout.AutoGenerateColors = false;
            this.btLogout.AutoRoundBorders = true;
            this.btLogout.AutoSizeLeftIcon = true;
            this.btLogout.AutoSizeRightIcon = true;
            this.btLogout.BackColor = System.Drawing.Color.Transparent;
            this.btLogout.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btLogout.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btLogout.BackgroundImage")));
            this.btLogout.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btLogout.ButtonText = "";
            this.btLogout.ButtonTextMarginLeft = 0;
            this.btLogout.ColorContrastOnClick = 45;
            this.btLogout.ColorContrastOnHover = 45;
            this.btLogout.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.btLogout.CustomizableEdges = borderEdges5;
            this.btLogout.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btLogout.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btLogout.DisabledFillColor = System.Drawing.Color.Empty;
            this.btLogout.DisabledForecolor = System.Drawing.Color.Empty;
            this.btLogout.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btLogout.Font = new System.Drawing.Font("Book Antiqua", 14.25F, ((System.Drawing.FontStyle)((System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Italic))), System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btLogout.ForeColor = System.Drawing.Color.Teal;
            this.btLogout.IconLeft = ((System.Drawing.Image)(resources.GetObject("btLogout.IconLeft")));
            this.btLogout.IconLeftAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btLogout.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btLogout.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btLogout.IconMarginLeft = 11;
            this.btLogout.IconPadding = 10;
            this.btLogout.IconRight = null;
            this.btLogout.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btLogout.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btLogout.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btLogout.IconSize = 25;
            this.btLogout.IdleBorderColor = System.Drawing.Color.Empty;
            this.btLogout.IdleBorderRadius = 0;
            this.btLogout.IdleBorderThickness = 0;
            this.btLogout.IdleFillColor = System.Drawing.Color.Empty;
            this.btLogout.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("btLogout.IdleIconLeftImage")));
            this.btLogout.IdleIconRightImage = null;
            this.btLogout.IndicateFocus = true;
            this.btLogout.Location = new System.Drawing.Point(1161, 12);
            this.btLogout.Name = "btLogout";
            this.btLogout.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btLogout.OnDisabledState.BorderRadius = 82;
            this.btLogout.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btLogout.OnDisabledState.BorderThickness = 1;
            this.btLogout.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btLogout.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btLogout.OnDisabledState.IconLeftImage = null;
            this.btLogout.OnDisabledState.IconRightImage = null;
            this.btLogout.onHoverState.BorderColor = System.Drawing.Color.Transparent;
            this.btLogout.onHoverState.BorderRadius = 82;
            this.btLogout.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btLogout.onHoverState.BorderThickness = 1;
            this.btLogout.onHoverState.FillColor = System.Drawing.Color.Transparent;
            this.btLogout.onHoverState.ForeColor = System.Drawing.Color.DodgerBlue;
            this.btLogout.onHoverState.IconLeftImage = null;
            this.btLogout.onHoverState.IconRightImage = null;
            this.btLogout.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.btLogout.OnIdleState.BorderRadius = 82;
            this.btLogout.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btLogout.OnIdleState.BorderThickness = 1;
            this.btLogout.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.btLogout.OnIdleState.ForeColor = System.Drawing.Color.Teal;
            this.btLogout.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("btLogout.OnIdleState.IconLeftImage")));
            this.btLogout.OnIdleState.IconRightImage = null;
            this.btLogout.OnPressedState.BorderColor = System.Drawing.Color.Transparent;
            this.btLogout.OnPressedState.BorderRadius = 82;
            this.btLogout.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btLogout.OnPressedState.BorderThickness = 1;
            this.btLogout.OnPressedState.FillColor = System.Drawing.Color.Transparent;
            this.btLogout.OnPressedState.ForeColor = System.Drawing.Color.DimGray;
            this.btLogout.OnPressedState.IconLeftImage = null;
            this.btLogout.OnPressedState.IconRightImage = null;
            this.btLogout.Size = new System.Drawing.Size(99, 82);
            this.btLogout.TabIndex = 3;
            this.btLogout.TabStop = false;
            this.btLogout.TextAlign = System.Drawing.ContentAlignment.BottomCenter;
            this.btLogout.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btLogout.TextMarginLeft = 0;
            this.btLogout.TextPadding = new System.Windows.Forms.Padding(0);
            this.toolTip1.SetToolTip(this.btLogout, "Trocar de usuário");
            this.btLogout.UseDefaultRadiusAndThickness = true;
            this.btLogout.Click += new System.EventHandler(this.btLogout_Click);
            // 
            // radGroupBox1
            // 
            this.radGroupBox1.AccessibleRole = System.Windows.Forms.AccessibleRole.Grouping;
            this.radGroupBox1.BackColor = System.Drawing.Color.WhiteSmoke;
            this.radGroupBox1.Controls.Add(this.lblStatus);
            this.radGroupBox1.Controls.Add(this.ItensPromo);
            this.radGroupBox1.Controls.Add(this.ItensVencendo);
            this.radGroupBox1.Controls.Add(this.OrcNo);
            this.radGroupBox1.Controls.Add(this.ValorEstq);
            this.radGroupBox1.Controls.Add(this.OrcYes);
            this.radGroupBox1.Controls.Add(this.OrcEspera);
            this.radGroupBox1.Controls.Add(this.TotalGast);
            this.radGroupBox1.Controls.Add(this.TotalVendasHj);
            this.radGroupBox1.Controls.Add(this.QuantClienAt);
            this.radGroupBox1.Controls.Add(this.QuantForn);
            this.radGroupBox1.Controls.Add(this.ProdEstoq);
            this.radGroupBox1.ForeColor = System.Drawing.Color.RoyalBlue;
            this.radGroupBox1.HeaderAlignment = Telerik.WinControls.UI.HeaderAlignment.Center;
            this.radGroupBox1.HeaderText = "DashBoard";
            this.radGroupBox1.Location = new System.Drawing.Point(12, 201);
            this.radGroupBox1.Name = "radGroupBox1";
            this.radGroupBox1.Size = new System.Drawing.Size(1248, 274);
            this.radGroupBox1.TabIndex = 4;
            this.radGroupBox1.Text = "DashBoard";
            this.radGroupBox1.ThemeName = "Aqua";
            // 
            // ItensPromo
            // 
            this.ItensPromo.AllowParentOverrides = false;
            this.ItensPromo.AutoEllipsis = false;
            this.ItensPromo.Cursor = System.Windows.Forms.Cursors.Default;
            this.ItensPromo.CursorType = System.Windows.Forms.Cursors.Default;
            this.ItensPromo.Font = new System.Drawing.Font("Arial Narrow", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.ItensPromo.ForeColor = System.Drawing.Color.OrangeRed;
            this.ItensPromo.Location = new System.Drawing.Point(544, 176);
            this.ItensPromo.Name = "ItensPromo";
            this.ItensPromo.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.ItensPromo.Size = new System.Drawing.Size(213, 21);
            this.ItensPromo.TabIndex = 19;
            this.ItensPromo.Text = "Quantidade de Itens em Promoção:";
            this.ItensPromo.TextAlignment = System.Drawing.ContentAlignment.MiddleLeft;
            this.ItensPromo.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // ItensVencendo
            // 
            this.ItensVencendo.AllowParentOverrides = false;
            this.ItensVencendo.AutoEllipsis = false;
            this.ItensVencendo.Cursor = System.Windows.Forms.Cursors.Default;
            this.ItensVencendo.CursorType = System.Windows.Forms.Cursors.Default;
            this.ItensVencendo.Font = new System.Drawing.Font("Arial Narrow", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.ItensVencendo.ForeColor = System.Drawing.Color.OrangeRed;
            this.ItensVencendo.Location = new System.Drawing.Point(5, 176);
            this.ItensVencendo.Name = "ItensVencendo";
            this.ItensVencendo.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.ItensVencendo.Size = new System.Drawing.Size(272, 21);
            this.ItensVencendo.TabIndex = 18;
            this.ItensVencendo.Text = "Quantidade de Itens Vencendo esta Semana:";
            this.ItensVencendo.TextAlignment = System.Drawing.ContentAlignment.MiddleLeft;
            this.ItensVencendo.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // OrcNo
            // 
            this.OrcNo.AllowParentOverrides = false;
            this.OrcNo.AutoEllipsis = false;
            this.OrcNo.Cursor = System.Windows.Forms.Cursors.Default;
            this.OrcNo.CursorType = System.Windows.Forms.Cursors.Default;
            this.OrcNo.Font = new System.Drawing.Font("Arial Narrow", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.OrcNo.ForeColor = System.Drawing.SystemColors.MenuHighlight;
            this.OrcNo.Location = new System.Drawing.Point(913, 102);
            this.OrcNo.Name = "OrcNo";
            this.OrcNo.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.OrcNo.Size = new System.Drawing.Size(174, 21);
            this.OrcNo.TabIndex = 17;
            this.OrcNo.Text = "Orçamentos Não-Aprovados:";
            this.OrcNo.TextAlignment = System.Drawing.ContentAlignment.MiddleLeft;
            this.OrcNo.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // ValorEstq
            // 
            this.ValorEstq.AllowParentOverrides = false;
            this.ValorEstq.AutoEllipsis = false;
            this.ValorEstq.Cursor = System.Windows.Forms.Cursors.Default;
            this.ValorEstq.CursorType = System.Windows.Forms.Cursors.Default;
            this.ValorEstq.Font = new System.Drawing.Font("Arial Narrow", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.ValorEstq.ForeColor = System.Drawing.SystemColors.MenuHighlight;
            this.ValorEstq.Location = new System.Drawing.Point(544, 99);
            this.ValorEstq.Name = "ValorEstq";
            this.ValorEstq.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.ValorEstq.Size = new System.Drawing.Size(144, 21);
            this.ValorEstq.TabIndex = 16;
            this.ValorEstq.Text = "Valor Total em Estoque:";
            this.ValorEstq.TextAlignment = System.Drawing.ContentAlignment.MiddleLeft;
            this.ValorEstq.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // OrcYes
            // 
            this.OrcYes.AllowParentOverrides = false;
            this.OrcYes.AutoEllipsis = false;
            this.OrcYes.Cursor = System.Windows.Forms.Cursors.Default;
            this.OrcYes.CursorType = System.Windows.Forms.Cursors.Default;
            this.OrcYes.Font = new System.Drawing.Font("Arial Narrow", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.OrcYes.ForeColor = System.Drawing.SystemColors.MenuHighlight;
            this.OrcYes.Location = new System.Drawing.Point(913, 66);
            this.OrcYes.Name = "OrcYes";
            this.OrcYes.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.OrcYes.Size = new System.Drawing.Size(146, 21);
            this.OrcYes.TabIndex = 15;
            this.OrcYes.Text = "Orçamentos Aprovados:";
            this.OrcYes.TextAlignment = System.Drawing.ContentAlignment.MiddleLeft;
            this.OrcYes.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // OrcEspera
            // 
            this.OrcEspera.AllowParentOverrides = false;
            this.OrcEspera.AutoEllipsis = false;
            this.OrcEspera.Cursor = System.Windows.Forms.Cursors.Default;
            this.OrcEspera.CursorType = System.Windows.Forms.Cursors.Default;
            this.OrcEspera.Font = new System.Drawing.Font("Arial Narrow", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.OrcEspera.ForeColor = System.Drawing.SystemColors.MenuHighlight;
            this.OrcEspera.Location = new System.Drawing.Point(913, 33);
            this.OrcEspera.Name = "OrcEspera";
            this.OrcEspera.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.OrcEspera.Size = new System.Drawing.Size(146, 21);
            this.OrcEspera.TabIndex = 14;
            this.OrcEspera.Text = "Orçamentos em Espera:";
            this.OrcEspera.TextAlignment = System.Drawing.ContentAlignment.MiddleLeft;
            this.OrcEspera.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // TotalGast
            // 
            this.TotalGast.AllowParentOverrides = false;
            this.TotalGast.AutoEllipsis = false;
            this.TotalGast.Cursor = System.Windows.Forms.Cursors.Default;
            this.TotalGast.CursorType = System.Windows.Forms.Cursors.Default;
            this.TotalGast.Font = new System.Drawing.Font("Arial Narrow", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.TotalGast.ForeColor = System.Drawing.SystemColors.MenuHighlight;
            this.TotalGast.Location = new System.Drawing.Point(544, 66);
            this.TotalGast.Name = "TotalGast";
            this.TotalGast.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.TotalGast.Size = new System.Drawing.Size(98, 21);
            this.TotalGast.TabIndex = 13;
            this.TotalGast.Text = "Total de Gastos:";
            this.TotalGast.TextAlignment = System.Drawing.ContentAlignment.MiddleLeft;
            this.TotalGast.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // TotalVendasHj
            // 
            this.TotalVendasHj.AllowParentOverrides = false;
            this.TotalVendasHj.AutoEllipsis = false;
            this.TotalVendasHj.Cursor = System.Windows.Forms.Cursors.Default;
            this.TotalVendasHj.CursorType = System.Windows.Forms.Cursors.Default;
            this.TotalVendasHj.Font = new System.Drawing.Font("Arial Narrow", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.TotalVendasHj.ForeColor = System.Drawing.SystemColors.MenuHighlight;
            this.TotalVendasHj.Location = new System.Drawing.Point(544, 33);
            this.TotalVendasHj.Name = "TotalVendasHj";
            this.TotalVendasHj.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.TotalVendasHj.Size = new System.Drawing.Size(132, 21);
            this.TotalVendasHj.TabIndex = 12;
            this.TotalVendasHj.Text = "Total de vendas Hoje:";
            this.TotalVendasHj.TextAlignment = System.Drawing.ContentAlignment.MiddleLeft;
            this.TotalVendasHj.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // QuantClienAt
            // 
            this.QuantClienAt.AllowParentOverrides = false;
            this.QuantClienAt.AutoEllipsis = false;
            this.QuantClienAt.Cursor = System.Windows.Forms.Cursors.Default;
            this.QuantClienAt.CursorType = System.Windows.Forms.Cursors.Default;
            this.QuantClienAt.Font = new System.Drawing.Font("Arial Narrow", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.QuantClienAt.ForeColor = System.Drawing.SystemColors.MenuHighlight;
            this.QuantClienAt.Location = new System.Drawing.Point(5, 99);
            this.QuantClienAt.Name = "QuantClienAt";
            this.QuantClienAt.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.QuantClienAt.Size = new System.Drawing.Size(185, 21);
            this.QuantClienAt.TabIndex = 11;
            this.QuantClienAt.Text = "Quantidade de Clientes Ativos:";
            this.QuantClienAt.TextAlignment = System.Drawing.ContentAlignment.MiddleLeft;
            this.QuantClienAt.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // QuantForn
            // 
            this.QuantForn.AllowParentOverrides = false;
            this.QuantForn.AutoEllipsis = false;
            this.QuantForn.Cursor = System.Windows.Forms.Cursors.Default;
            this.QuantForn.CursorType = System.Windows.Forms.Cursors.Default;
            this.QuantForn.Font = new System.Drawing.Font("Arial Narrow", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.QuantForn.ForeColor = System.Drawing.SystemColors.MenuHighlight;
            this.QuantForn.Location = new System.Drawing.Point(5, 66);
            this.QuantForn.Name = "QuantForn";
            this.QuantForn.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.QuantForn.Size = new System.Drawing.Size(181, 21);
            this.QuantForn.TabIndex = 10;
            this.QuantForn.Text = "Quantidade de Fornecedores:";
            this.QuantForn.TextAlignment = System.Drawing.ContentAlignment.MiddleLeft;
            this.QuantForn.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // ProdEstoq
            // 
            this.ProdEstoq.AllowParentOverrides = false;
            this.ProdEstoq.AutoEllipsis = false;
            this.ProdEstoq.Cursor = System.Windows.Forms.Cursors.Default;
            this.ProdEstoq.CursorType = System.Windows.Forms.Cursors.Default;
            this.ProdEstoq.Font = new System.Drawing.Font("Arial Narrow", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.ProdEstoq.ForeColor = System.Drawing.SystemColors.MenuHighlight;
            this.ProdEstoq.Location = new System.Drawing.Point(5, 33);
            this.ProdEstoq.Name = "ProdEstoq";
            this.ProdEstoq.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.ProdEstoq.Size = new System.Drawing.Size(226, 21);
            this.ProdEstoq.TabIndex = 9;
            this.ProdEstoq.Text = "Quantidade de Produtos em estoque:";
            this.ProdEstoq.TextAlignment = System.Drawing.ContentAlignment.MiddleLeft;
            this.ProdEstoq.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // radGroupBox2
            // 
            this.radGroupBox2.AccessibleRole = System.Windows.Forms.AccessibleRole.Grouping;
            this.radGroupBox2.BackColor = System.Drawing.Color.WhiteSmoke;
            this.radGroupBox2.Controls.Add(this.btAprovarOrcamentos);
            this.radGroupBox2.Controls.Add(this.lbMsg2);
            this.radGroupBox2.Controls.Add(this.btVendas);
            this.radGroupBox2.Controls.Add(this.btOrcamentos);
            this.radGroupBox2.HeaderAlignment = Telerik.WinControls.UI.HeaderAlignment.Center;
            this.radGroupBox2.HeaderText = "Atendimento";
            this.radGroupBox2.Location = new System.Drawing.Point(650, 12);
            this.radGroupBox2.Name = "radGroupBox2";
            this.radGroupBox2.Size = new System.Drawing.Size(395, 153);
            this.radGroupBox2.TabIndex = 5;
            this.radGroupBox2.Text = "Atendimento";
            this.radGroupBox2.ThemeName = "Aqua";
            // 
            // lbMsg2
            // 
            this.lbMsg2.AllowParentOverrides = false;
            this.lbMsg2.AutoEllipsis = false;
            this.lbMsg2.AutoSize = false;
            this.lbMsg2.Cursor = System.Windows.Forms.Cursors.Default;
            this.lbMsg2.CursorType = System.Windows.Forms.Cursors.Default;
            this.lbMsg2.Font = new System.Drawing.Font("Yu Gothic UI", 12F, ((System.Drawing.FontStyle)((System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Italic))));
            this.lbMsg2.ForeColor = System.Drawing.SystemColors.MenuHighlight;
            this.lbMsg2.Location = new System.Drawing.Point(56, 121);
            this.lbMsg2.Name = "lbMsg2";
            this.lbMsg2.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.lbMsg2.Size = new System.Drawing.Size(278, 27);
            this.lbMsg2.TabIndex = 8;
            this.lbMsg2.Text = "Mensagem";
            this.lbMsg2.TextAlignment = System.Drawing.ContentAlignment.MiddleCenter;
            this.lbMsg2.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.lbMsg2.Visible = false;
            // 
            // btVendas
            // 
            this.btVendas.AllowAnimations = true;
            this.btVendas.AllowMouseEffects = true;
            this.btVendas.AllowToggling = true;
            this.btVendas.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.btVendas.AnimationSpeed = 200;
            this.btVendas.AutoGenerateColors = false;
            this.btVendas.AutoRoundBorders = true;
            this.btVendas.AutoSizeLeftIcon = true;
            this.btVendas.AutoSizeRightIcon = true;
            this.btVendas.BackColor = System.Drawing.Color.Transparent;
            this.btVendas.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btVendas.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btVendas.BackgroundImage")));
            this.btVendas.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btVendas.ButtonText = "";
            this.btVendas.ButtonTextMarginLeft = 0;
            this.btVendas.ColorContrastOnClick = 45;
            this.btVendas.ColorContrastOnHover = 45;
            this.btVendas.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges7.BottomLeft = true;
            borderEdges7.BottomRight = true;
            borderEdges7.TopLeft = true;
            borderEdges7.TopRight = true;
            this.btVendas.CustomizableEdges = borderEdges7;
            this.btVendas.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btVendas.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btVendas.DisabledFillColor = System.Drawing.Color.Empty;
            this.btVendas.DisabledForecolor = System.Drawing.Color.Empty;
            this.btVendas.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btVendas.Font = new System.Drawing.Font("Book Antiqua", 14.25F, ((System.Drawing.FontStyle)((System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Italic))), System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btVendas.ForeColor = System.Drawing.Color.Teal;
            this.btVendas.IconLeft = ((System.Drawing.Image)(resources.GetObject("btVendas.IconLeft")));
            this.btVendas.IconLeftAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btVendas.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btVendas.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btVendas.IconMarginLeft = 11;
            this.btVendas.IconPadding = 10;
            this.btVendas.IconRight = null;
            this.btVendas.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btVendas.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btVendas.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btVendas.IconSize = 25;
            this.btVendas.IdleBorderColor = System.Drawing.Color.Empty;
            this.btVendas.IdleBorderRadius = 0;
            this.btVendas.IdleBorderThickness = 0;
            this.btVendas.IdleFillColor = System.Drawing.Color.Empty;
            this.btVendas.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("btVendas.IdleIconLeftImage")));
            this.btVendas.IdleIconRightImage = null;
            this.btVendas.IndicateFocus = true;
            this.btVendas.Location = new System.Drawing.Point(248, 33);
            this.btVendas.Name = "btVendas";
            this.btVendas.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btVendas.OnDisabledState.BorderRadius = 82;
            this.btVendas.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btVendas.OnDisabledState.BorderThickness = 1;
            this.btVendas.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btVendas.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btVendas.OnDisabledState.IconLeftImage = null;
            this.btVendas.OnDisabledState.IconRightImage = null;
            this.btVendas.onHoverState.BorderColor = System.Drawing.Color.Transparent;
            this.btVendas.onHoverState.BorderRadius = 82;
            this.btVendas.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btVendas.onHoverState.BorderThickness = 1;
            this.btVendas.onHoverState.FillColor = System.Drawing.Color.Transparent;
            this.btVendas.onHoverState.ForeColor = System.Drawing.Color.DodgerBlue;
            this.btVendas.onHoverState.IconLeftImage = null;
            this.btVendas.onHoverState.IconRightImage = null;
            this.btVendas.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.btVendas.OnIdleState.BorderRadius = 82;
            this.btVendas.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btVendas.OnIdleState.BorderThickness = 1;
            this.btVendas.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.btVendas.OnIdleState.ForeColor = System.Drawing.Color.Teal;
            this.btVendas.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("btVendas.OnIdleState.IconLeftImage")));
            this.btVendas.OnIdleState.IconRightImage = null;
            this.btVendas.OnPressedState.BorderColor = System.Drawing.Color.Transparent;
            this.btVendas.OnPressedState.BorderRadius = 82;
            this.btVendas.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btVendas.OnPressedState.BorderThickness = 1;
            this.btVendas.OnPressedState.FillColor = System.Drawing.Color.Transparent;
            this.btVendas.OnPressedState.ForeColor = System.Drawing.Color.DimGray;
            this.btVendas.OnPressedState.IconLeftImage = null;
            this.btVendas.OnPressedState.IconRightImage = null;
            this.btVendas.Size = new System.Drawing.Size(99, 82);
            this.btVendas.TabIndex = 6;
            this.btVendas.TabStop = false;
            this.btVendas.TextAlign = System.Drawing.ContentAlignment.BottomCenter;
            this.btVendas.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btVendas.TextMarginLeft = 0;
            this.btVendas.TextPadding = new System.Windows.Forms.Padding(0);
            this.btVendas.UseDefaultRadiusAndThickness = true;
            this.btVendas.Click += new System.EventHandler(this.btVendas_Click);
            // 
            // btOrcamentos
            // 
            this.btOrcamentos.AllowAnimations = true;
            this.btOrcamentos.AllowMouseEffects = true;
            this.btOrcamentos.AllowToggling = true;
            this.btOrcamentos.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.btOrcamentos.AnimationSpeed = 200;
            this.btOrcamentos.AutoGenerateColors = false;
            this.btOrcamentos.AutoRoundBorders = true;
            this.btOrcamentos.AutoSizeLeftIcon = true;
            this.btOrcamentos.AutoSizeRightIcon = true;
            this.btOrcamentos.BackColor = System.Drawing.Color.Transparent;
            this.btOrcamentos.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btOrcamentos.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btOrcamentos.BackgroundImage")));
            this.btOrcamentos.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btOrcamentos.ButtonText = "";
            this.btOrcamentos.ButtonTextMarginLeft = 0;
            this.btOrcamentos.ColorContrastOnClick = 45;
            this.btOrcamentos.ColorContrastOnHover = 45;
            this.btOrcamentos.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges8.BottomLeft = true;
            borderEdges8.BottomRight = true;
            borderEdges8.TopLeft = true;
            borderEdges8.TopRight = true;
            this.btOrcamentos.CustomizableEdges = borderEdges8;
            this.btOrcamentos.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btOrcamentos.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btOrcamentos.DisabledFillColor = System.Drawing.Color.Empty;
            this.btOrcamentos.DisabledForecolor = System.Drawing.Color.Empty;
            this.btOrcamentos.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btOrcamentos.Font = new System.Drawing.Font("Book Antiqua", 14.25F, ((System.Drawing.FontStyle)((System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Italic))), System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btOrcamentos.ForeColor = System.Drawing.Color.Teal;
            this.btOrcamentos.IconLeft = ((System.Drawing.Image)(resources.GetObject("btOrcamentos.IconLeft")));
            this.btOrcamentos.IconLeftAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btOrcamentos.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btOrcamentos.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btOrcamentos.IconMarginLeft = 11;
            this.btOrcamentos.IconPadding = 10;
            this.btOrcamentos.IconRight = null;
            this.btOrcamentos.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btOrcamentos.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btOrcamentos.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btOrcamentos.IconSize = 25;
            this.btOrcamentos.IdleBorderColor = System.Drawing.Color.Empty;
            this.btOrcamentos.IdleBorderRadius = 0;
            this.btOrcamentos.IdleBorderThickness = 0;
            this.btOrcamentos.IdleFillColor = System.Drawing.Color.Empty;
            this.btOrcamentos.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("btOrcamentos.IdleIconLeftImage")));
            this.btOrcamentos.IdleIconRightImage = null;
            this.btOrcamentos.IndicateFocus = true;
            this.btOrcamentos.Location = new System.Drawing.Point(29, 33);
            this.btOrcamentos.Name = "btOrcamentos";
            this.btOrcamentos.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btOrcamentos.OnDisabledState.BorderRadius = 82;
            this.btOrcamentos.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btOrcamentos.OnDisabledState.BorderThickness = 1;
            this.btOrcamentos.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btOrcamentos.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btOrcamentos.OnDisabledState.IconLeftImage = null;
            this.btOrcamentos.OnDisabledState.IconRightImage = null;
            this.btOrcamentos.onHoverState.BorderColor = System.Drawing.Color.Transparent;
            this.btOrcamentos.onHoverState.BorderRadius = 82;
            this.btOrcamentos.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btOrcamentos.onHoverState.BorderThickness = 1;
            this.btOrcamentos.onHoverState.FillColor = System.Drawing.Color.Transparent;
            this.btOrcamentos.onHoverState.ForeColor = System.Drawing.Color.DodgerBlue;
            this.btOrcamentos.onHoverState.IconLeftImage = null;
            this.btOrcamentos.onHoverState.IconRightImage = null;
            this.btOrcamentos.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.btOrcamentos.OnIdleState.BorderRadius = 82;
            this.btOrcamentos.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btOrcamentos.OnIdleState.BorderThickness = 1;
            this.btOrcamentos.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.btOrcamentos.OnIdleState.ForeColor = System.Drawing.Color.Teal;
            this.btOrcamentos.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("btOrcamentos.OnIdleState.IconLeftImage")));
            this.btOrcamentos.OnIdleState.IconRightImage = null;
            this.btOrcamentos.OnPressedState.BorderColor = System.Drawing.Color.Transparent;
            this.btOrcamentos.OnPressedState.BorderRadius = 82;
            this.btOrcamentos.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btOrcamentos.OnPressedState.BorderThickness = 1;
            this.btOrcamentos.OnPressedState.FillColor = System.Drawing.Color.Transparent;
            this.btOrcamentos.OnPressedState.ForeColor = System.Drawing.Color.DimGray;
            this.btOrcamentos.OnPressedState.IconLeftImage = null;
            this.btOrcamentos.OnPressedState.IconRightImage = null;
            this.btOrcamentos.Size = new System.Drawing.Size(99, 82);
            this.btOrcamentos.TabIndex = 5;
            this.btOrcamentos.TabStop = false;
            this.btOrcamentos.TextAlign = System.Drawing.ContentAlignment.BottomCenter;
            this.btOrcamentos.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btOrcamentos.TextMarginLeft = 0;
            this.btOrcamentos.TextPadding = new System.Windows.Forms.Padding(0);
            this.btOrcamentos.UseDefaultRadiusAndThickness = true;
            this.btOrcamentos.Click += new System.EventHandler(this.btOrcamentos_Click);
            // 
            // btAprovarOrcamentos
            // 
            this.btAprovarOrcamentos.AllowAnimations = true;
            this.btAprovarOrcamentos.AllowMouseEffects = true;
            this.btAprovarOrcamentos.AllowToggling = true;
            this.btAprovarOrcamentos.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.btAprovarOrcamentos.AnimationSpeed = 200;
            this.btAprovarOrcamentos.AutoGenerateColors = false;
            this.btAprovarOrcamentos.AutoRoundBorders = true;
            this.btAprovarOrcamentos.AutoSizeLeftIcon = true;
            this.btAprovarOrcamentos.AutoSizeRightIcon = true;
            this.btAprovarOrcamentos.BackColor = System.Drawing.Color.Transparent;
            this.btAprovarOrcamentos.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btAprovarOrcamentos.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btAprovarOrcamentos.BackgroundImage")));
            this.btAprovarOrcamentos.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btAprovarOrcamentos.ButtonText = "";
            this.btAprovarOrcamentos.ButtonTextMarginLeft = 0;
            this.btAprovarOrcamentos.ColorContrastOnClick = 45;
            this.btAprovarOrcamentos.ColorContrastOnHover = 45;
            this.btAprovarOrcamentos.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.btAprovarOrcamentos.CustomizableEdges = borderEdges6;
            this.btAprovarOrcamentos.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btAprovarOrcamentos.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btAprovarOrcamentos.DisabledFillColor = System.Drawing.Color.Empty;
            this.btAprovarOrcamentos.DisabledForecolor = System.Drawing.Color.Empty;
            this.btAprovarOrcamentos.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btAprovarOrcamentos.Font = new System.Drawing.Font("Book Antiqua", 14.25F, ((System.Drawing.FontStyle)((System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Italic))), System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btAprovarOrcamentos.ForeColor = System.Drawing.Color.Teal;
            this.btAprovarOrcamentos.IconLeft = ((System.Drawing.Image)(resources.GetObject("btAprovarOrcamentos.IconLeft")));
            this.btAprovarOrcamentos.IconLeftAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btAprovarOrcamentos.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btAprovarOrcamentos.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btAprovarOrcamentos.IconMarginLeft = 11;
            this.btAprovarOrcamentos.IconPadding = 10;
            this.btAprovarOrcamentos.IconRight = null;
            this.btAprovarOrcamentos.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btAprovarOrcamentos.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btAprovarOrcamentos.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btAprovarOrcamentos.IconSize = 25;
            this.btAprovarOrcamentos.IdleBorderColor = System.Drawing.Color.Empty;
            this.btAprovarOrcamentos.IdleBorderRadius = 0;
            this.btAprovarOrcamentos.IdleBorderThickness = 0;
            this.btAprovarOrcamentos.IdleFillColor = System.Drawing.Color.Empty;
            this.btAprovarOrcamentos.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("btAprovarOrcamentos.IdleIconLeftImage")));
            this.btAprovarOrcamentos.IdleIconRightImage = null;
            this.btAprovarOrcamentos.IndicateFocus = true;
            this.btAprovarOrcamentos.Location = new System.Drawing.Point(134, 33);
            this.btAprovarOrcamentos.Name = "btAprovarOrcamentos";
            this.btAprovarOrcamentos.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btAprovarOrcamentos.OnDisabledState.BorderRadius = 82;
            this.btAprovarOrcamentos.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btAprovarOrcamentos.OnDisabledState.BorderThickness = 1;
            this.btAprovarOrcamentos.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btAprovarOrcamentos.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btAprovarOrcamentos.OnDisabledState.IconLeftImage = null;
            this.btAprovarOrcamentos.OnDisabledState.IconRightImage = null;
            this.btAprovarOrcamentos.onHoverState.BorderColor = System.Drawing.Color.Transparent;
            this.btAprovarOrcamentos.onHoverState.BorderRadius = 82;
            this.btAprovarOrcamentos.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btAprovarOrcamentos.onHoverState.BorderThickness = 1;
            this.btAprovarOrcamentos.onHoverState.FillColor = System.Drawing.Color.Transparent;
            this.btAprovarOrcamentos.onHoverState.ForeColor = System.Drawing.Color.DodgerBlue;
            this.btAprovarOrcamentos.onHoverState.IconLeftImage = null;
            this.btAprovarOrcamentos.onHoverState.IconRightImage = null;
            this.btAprovarOrcamentos.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.btAprovarOrcamentos.OnIdleState.BorderRadius = 82;
            this.btAprovarOrcamentos.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btAprovarOrcamentos.OnIdleState.BorderThickness = 1;
            this.btAprovarOrcamentos.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.btAprovarOrcamentos.OnIdleState.ForeColor = System.Drawing.Color.Teal;
            this.btAprovarOrcamentos.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton21.OnIdleState.IconLeftImage")));
            this.btAprovarOrcamentos.OnIdleState.IconRightImage = null;
            this.btAprovarOrcamentos.OnPressedState.BorderColor = System.Drawing.Color.Transparent;
            this.btAprovarOrcamentos.OnPressedState.BorderRadius = 82;
            this.btAprovarOrcamentos.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btAprovarOrcamentos.OnPressedState.BorderThickness = 1;
            this.btAprovarOrcamentos.OnPressedState.FillColor = System.Drawing.Color.Transparent;
            this.btAprovarOrcamentos.OnPressedState.ForeColor = System.Drawing.Color.DimGray;
            this.btAprovarOrcamentos.OnPressedState.IconLeftImage = null;
            this.btAprovarOrcamentos.OnPressedState.IconRightImage = null;
            this.btAprovarOrcamentos.Size = new System.Drawing.Size(99, 82);
            this.btAprovarOrcamentos.TabIndex = 9;
            this.btAprovarOrcamentos.TabStop = false;
            this.btAprovarOrcamentos.TextAlign = System.Drawing.ContentAlignment.BottomCenter;
            this.btAprovarOrcamentos.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btAprovarOrcamentos.TextMarginLeft = 0;
            this.btAprovarOrcamentos.TextPadding = new System.Windows.Forms.Padding(0);
            this.btAprovarOrcamentos.UseDefaultRadiusAndThickness = true;
            this.btAprovarOrcamentos.Click += new System.EventHandler(this.btAprovarOrcamentos_Click);
            // 
            // lblStatus
            // 
            this.lblStatus.AllowParentOverrides = false;
            this.lblStatus.AutoEllipsis = false;
            this.lblStatus.Cursor = System.Windows.Forms.Cursors.Default;
            this.lblStatus.CursorType = System.Windows.Forms.Cursors.Default;
            this.lblStatus.Font = new System.Drawing.Font("Yu Gothic UI", 12F, ((System.Drawing.FontStyle)((System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Italic))));
            this.lblStatus.ForeColor = System.Drawing.Color.OrangeRed;
            this.lblStatus.Location = new System.Drawing.Point(5, 248);
            this.lblStatus.Name = "lblStatus";
            this.lblStatus.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.lblStatus.Size = new System.Drawing.Size(102, 21);
            this.lblStatus.TabIndex = 20;
            this.lblStatus.Text = "Carregando....";
            this.lblStatus.TextAlignment = System.Drawing.ContentAlignment.MiddleLeft;
            this.lblStatus.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // Geral
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.WhiteSmoke;
            this.ClientSize = new System.Drawing.Size(1272, 728);
            this.Controls.Add(this.radGroupBox2);
            this.Controls.Add(this.radGroupBox1);
            this.Controls.Add(this.btLogout);
            this.Controls.Add(this.gb1);
            this.Controls.Add(this.pictureBox1);
            this.Controls.Add(this.lbusuario);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedSingle;
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.KeyPreview = true;
            this.Name = "Geral";
            this.Text = "";
            this.FormClosing += new System.Windows.Forms.FormClosingEventHandler(this.Geral_FormClosing);
            this.Load += new System.EventHandler(this.Geral_Load);
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.gb1)).EndInit();
            this.gb1.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.radGroupBox1)).EndInit();
            this.radGroupBox1.ResumeLayout(false);
            this.radGroupBox1.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.radGroupBox2)).EndInit();
            this.radGroupBox2.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuFormControlBox bunifuFormControlBox1;
        private Bunifu.UI.WinForms.BunifuImageButton btnLogout;
        private Bunifu.UI.WinForms.BunifuPictureBox bunifuPictureBox1;
        private Telerik.WinControls.Themes.AquaTheme aquaTheme1;
        private Telerik.WinControls.Themes.MaterialTheme materialTheme1;
        private Bunifu.UI.WinForms.BunifuImageButton btUsuarios;
        private Bunifu.UI.WinForms.BunifuImageButton btFornecedores;
        private Bunifu.UI.WinForms.BunifuImageButton btProdutos;
        private Telerik.WinControls.UI.RadFormConverter radFormConverter1;
        private Bunifu.UI.WinForms.BunifuLabel lbusuario;
        private System.Windows.Forms.PictureBox pictureBox1;
        private Telerik.WinControls.UI.RadGroupBox gb1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btLogout;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 bt4;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 bt3;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 bt2;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 bt1;
        private Bunifu.UI.WinForms.BunifuLabel lbMsg;
        private System.Windows.Forms.ToolTip toolTip1;
        private Telerik.WinControls.UI.RadGroupBox radGroupBox1;
        private Telerik.WinControls.UI.RadGroupBox radGroupBox2;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btOrcamentos;
        private Bunifu.UI.WinForms.BunifuLabel lbMsg2;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btVendas;
        private Bunifu.UI.WinForms.BunifuLabel QuantClienAt;
        private Bunifu.UI.WinForms.BunifuLabel QuantForn;
        private Bunifu.UI.WinForms.BunifuLabel ProdEstoq;
        private Bunifu.UI.WinForms.BunifuLabel TotalGast;
        private Bunifu.UI.WinForms.BunifuLabel TotalVendasHj;
        private Bunifu.UI.WinForms.BunifuLabel OrcNo;
        private Bunifu.UI.WinForms.BunifuLabel ValorEstq;
        private Bunifu.UI.WinForms.BunifuLabel OrcYes;
        private Bunifu.UI.WinForms.BunifuLabel OrcEspera;
        private Bunifu.UI.WinForms.BunifuLabel ItensPromo;
        private Bunifu.UI.WinForms.BunifuLabel ItensVencendo;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btAprovarOrcamentos;
        private Bunifu.UI.WinForms.BunifuLabel lblStatus;
    }
}
